source "https://rubygems.org"

# Specify your gem's dependencies in okapi.gemspec
gemspec

gem "rake"
gem 'google-protobuf'
gem "os"
gem "base64"
gem "ffi"
gem 'base58'

group :test do
  gem "simplecov", require: false
  gem "simplecov-cobertura", require: false
end

group :development do
  gem "minitest", "~> 5.0"
  gem 'rbs_protobuf', require: false
  gem 'rbs'
end