source "https://rubygems.org"

# Specify your gem's dependencies in okapi.gemspec
gemspec

gem "rake", "~> 12.0"
gem "minitest", "~> 5.0"
gem "simplecov", require: false, group: :test
gem "simplecov-cobertura", require: false, group: :test
gem 'google-protobuf', '~> 4.0.0.rc.2'
gem "os"
gem "base64"

gem "ffi"
gem 'base58'

group :development do
  gem 'rbs_protobuf', require: false
  gem 'rbs'
end