source "https://rubygems.org"

# Specify your gem's dependencies in okapi.gemspec
gemspec

group :test do
  gem "simplecov", require: false
  gem "simplecov-cobertura", require: false
end

group :development do
  gem 'rbs_protobuf', require: false
  gem 'rbs'
end