jobs:
- job: Package_Nuget

  pool:
    vmImage: 'macos-latest'
  variables:
    solution: '**/*.sln'
    buildConfiguration: 'Release'

  steps:

  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'current'
      downloadType: 'specific'
      itemPattern: |
        **/*.a
        **/*.dylib
        **/*.so
        **/*.dll
      downloadPath: '$(Build.SourcesDirectory)/libs'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      projects: '$(solution)'
      feedsToUse: 'select'

  - task: MSBuild@1
    inputs:
      solution: '**/*.sln'
      configuration: '$(buildConfiguration)'
      msbuildArguments: '/t:build,pack /p:PackageOutputPath=$(Build.SourcesDirectory)/dotnet/nuget'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.SourcesDirectory)/dotnet/nuget/'
      ArtifactName: 'nuget'
      publishLocation: 'Container'