name: okapi_dart
description: Dart language bindings for okapi
version: 0.1.0
homepage: 'https://github.com/trinsic-id/okapi/'

environment:
  sdk: '>=2.15.1 <3.0.0'


dependencies:
  ffi: ^1.0.0
  protobuf: ^2.0.1
  path: ^1.8.1

dev_dependencies:
  lints: ^1.0.0
  test: ^1.21.1
  convert: any
  fast_base58: any