name: okapi_dart
description: Dart language bindings for okapi
version: "1.6.0"
homepage: 'https://github.com/trinsic-id/okapi/'

environment:
  sdk: '>=2.16.2 <3.0.0'


dependencies:
  ffi: ^1.1.2
  protobuf: ^2.0.0
  path: ^1.8.1
  fixnum: ^1.0.1

dev_dependencies:
  lints: any
  test: ^1.16.0
  convert: any
  fast_base58: any
  coverage: ^1.3.2