//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: okapi/security/v1/security.proto

package trinsic.okapi.security.v1;

@kotlin.jvm.JvmSynthetic
inline fun unBlindOberonTokenResponse(block: trinsic.okapi.security.v1.UnBlindOberonTokenResponseKt.Dsl.() -> Unit): trinsic.okapi.security.v1.Security.UnBlindOberonTokenResponse =
  trinsic.okapi.security.v1.UnBlindOberonTokenResponseKt.Dsl._create(trinsic.okapi.security.v1.Security.UnBlindOberonTokenResponse.newBuilder()).apply { block() }._build()
object UnBlindOberonTokenResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: trinsic.okapi.security.v1.Security.UnBlindOberonTokenResponse.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: trinsic.okapi.security.v1.Security.UnBlindOberonTokenResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): trinsic.okapi.security.v1.Security.UnBlindOberonTokenResponse = _builder.build()

    /**
     * <pre>
     * raw unblinded token bytes
     * </pre>
     *
     * <code>bytes token = 1;</code>
     */
    var token: com.google.protobuf.ByteString
      @JvmName("getToken")
      get() = _builder.getToken()
      @JvmName("setToken")
      set(value) {
        _builder.setToken(value)
      }
    /**
     * <pre>
     * raw unblinded token bytes
     * </pre>
     *
     * <code>bytes token = 1;</code>
     */
    fun clearToken() {
      _builder.clearToken()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun trinsic.okapi.security.v1.Security.UnBlindOberonTokenResponse.copy(block: trinsic.okapi.security.v1.UnBlindOberonTokenResponseKt.Dsl.() -> Unit): trinsic.okapi.security.v1.Security.UnBlindOberonTokenResponse =
  trinsic.okapi.security.v1.UnBlindOberonTokenResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()
