//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: okapi/security/v1/security.proto

package trinsic.okapi.security.v1;

@kotlin.jvm.JvmName("-initializeverifyOberonTokenResponse")
public inline fun verifyOberonTokenResponse(block: trinsic.okapi.security.v1.VerifyOberonTokenResponseKt.Dsl.() -> kotlin.Unit): trinsic.okapi.security.v1.Security.VerifyOberonTokenResponse =
  trinsic.okapi.security.v1.VerifyOberonTokenResponseKt.Dsl._create(trinsic.okapi.security.v1.Security.VerifyOberonTokenResponse.newBuilder()).apply { block() }._build()
public object VerifyOberonTokenResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: trinsic.okapi.security.v1.Security.VerifyOberonTokenResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: trinsic.okapi.security.v1.Security.VerifyOberonTokenResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): trinsic.okapi.security.v1.Security.VerifyOberonTokenResponse = _builder.build()

    /**
     * <pre>
     * token is valid to the public key
     * </pre>
     *
     * <code>bool valid = 1;</code>
     */
    public var valid: kotlin.Boolean
      @JvmName("getValid")
      get() = _builder.getValid()
      @JvmName("setValid")
      set(value) {
        _builder.setValid(value)
      }
    /**
     * <pre>
     * token is valid to the public key
     * </pre>
     *
     * <code>bool valid = 1;</code>
     */
    public fun clearValid() {
      _builder.clearValid()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun trinsic.okapi.security.v1.Security.VerifyOberonTokenResponse.copy(block: trinsic.okapi.security.v1.VerifyOberonTokenResponseKt.Dsl.() -> kotlin.Unit): trinsic.okapi.security.v1.Security.VerifyOberonTokenResponse =
  trinsic.okapi.security.v1.VerifyOberonTokenResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

