//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: okapi/security/v1/security.proto

package trinsic.okapi.security.v1;

@kotlin.jvm.JvmName("-initializeverifyOberonProofResponse")
public inline fun verifyOberonProofResponse(block: trinsic.okapi.security.v1.VerifyOberonProofResponseKt.Dsl.() -> kotlin.Unit): trinsic.okapi.security.v1.Security.VerifyOberonProofResponse =
  trinsic.okapi.security.v1.VerifyOberonProofResponseKt.Dsl._create(trinsic.okapi.security.v1.Security.VerifyOberonProofResponse.newBuilder()).apply { block() }._build()
public object VerifyOberonProofResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: trinsic.okapi.security.v1.Security.VerifyOberonProofResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: trinsic.okapi.security.v1.Security.VerifyOberonProofResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): trinsic.okapi.security.v1.Security.VerifyOberonProofResponse = _builder.build()

    /**
     * <pre>
     * whether the given proof was valid
     * </pre>
     *
     * <code>bool valid = 1;</code>
     */
    public var valid: kotlin.Boolean
      @JvmName("getValid")
      get() = _builder.getValid()
      @JvmName("setValid")
      set(value) {
        _builder.setValid(value)
      }
    /**
     * <pre>
     * whether the given proof was valid
     * </pre>
     *
     * <code>bool valid = 1;</code>
     */
    public fun clearValid() {
      _builder.clearValid()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun trinsic.okapi.security.v1.Security.VerifyOberonProofResponse.copy(block: trinsic.okapi.security.v1.VerifyOberonProofResponseKt.Dsl.() -> kotlin.Unit): trinsic.okapi.security.v1.Security.VerifyOberonProofResponse =
  trinsic.okapi.security.v1.VerifyOberonProofResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

