# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: okapi/examples/v1/examples.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import AsyncGenerator

import betterproto
import grpclib

from .pbmse import v1


@dataclass
class BasicMessage(betterproto.Message):
    text: str = betterproto.string_field(1)


class SecureExampleServiceStub(betterproto.ServiceStub):
    async def unary(self) -> v1.EncryptedMessage:
        request = v1.EncryptedMessage()

        return await self._unary_unary(
            "/okapi.examples.v1.SecureExampleService/Unary",
            request,
            v1.EncryptedMessage,
        )

    async def server_streaming(self) -> AsyncGenerator[v1.EncryptedMessage, None]:
        request = v1.EncryptedMessage()

        async for response in self._unary_stream(
            "/okapi.examples.v1.SecureExampleService/ServerStreaming",
            request,
            v1.EncryptedMessage,
        ):
            yield response
