// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proofs.proto

package trinsic.okapi.proofs;

public interface VerifyProofRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:okapi.proofs.VerifyProofRequest)
    com.google.protobuf.MessageOrBuilder {
}
