// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: keys.proto

package trinsic.okapi.keys;

public interface GenerateKeyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:okapi.keys.GenerateKeyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes seed = 1;</code>
   * @return The seed.
   */
  com.google.protobuf.ByteString getSeed();

  /**
   * <code>.okapi.keys.KeyType key_type = 2;</code>
   * @return The enum numeric value on the wire for keyType.
   */
  int getKeyTypeValue();
  /**
   * <code>.okapi.keys.KeyType key_type = 2;</code>
   * @return The keyType.
   */
  trinsic.okapi.keys.KeyType getKeyType();
}
