// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: keys.proto

package trinsic.okapi.keys;

/**
 * Protobuf type {@code okapi.keys.GenerateKeyResponse}
 */
public final class GenerateKeyResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:okapi.keys.GenerateKeyResponse)
    GenerateKeyResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GenerateKeyResponse.newBuilder() to construct.
  private GenerateKeyResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GenerateKeyResponse() {
    key_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GenerateKeyResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GenerateKeyResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              key_ = new java.util.ArrayList<trinsic.okapi.keys.JsonWebKey>();
              mutable_bitField0_ |= 0x00000001;
            }
            key_.add(
                input.readMessage(trinsic.okapi.keys.JsonWebKey.parser(), extensionRegistry));
            break;
          }
          case 18: {
            com.google.protobuf.Struct.Builder subBuilder = null;
            if (didDocument_ != null) {
              subBuilder = didDocument_.toBuilder();
            }
            didDocument_ = input.readMessage(com.google.protobuf.Struct.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(didDocument_);
              didDocument_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        key_ = java.util.Collections.unmodifiableList(key_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return trinsic.okapi.keys.Keys.internal_static_okapi_keys_GenerateKeyResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return trinsic.okapi.keys.Keys.internal_static_okapi_keys_GenerateKeyResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            trinsic.okapi.keys.GenerateKeyResponse.class, trinsic.okapi.keys.GenerateKeyResponse.Builder.class);
  }

  public static final int KEY_FIELD_NUMBER = 1;
  private java.util.List<trinsic.okapi.keys.JsonWebKey> key_;
  /**
   * <code>repeated .okapi.keys.JsonWebKey key = 1;</code>
   */
  @java.lang.Override
  public java.util.List<trinsic.okapi.keys.JsonWebKey> getKeyList() {
    return key_;
  }
  /**
   * <code>repeated .okapi.keys.JsonWebKey key = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends trinsic.okapi.keys.JsonWebKeyOrBuilder> 
      getKeyOrBuilderList() {
    return key_;
  }
  /**
   * <code>repeated .okapi.keys.JsonWebKey key = 1;</code>
   */
  @java.lang.Override
  public int getKeyCount() {
    return key_.size();
  }
  /**
   * <code>repeated .okapi.keys.JsonWebKey key = 1;</code>
   */
  @java.lang.Override
  public trinsic.okapi.keys.JsonWebKey getKey(int index) {
    return key_.get(index);
  }
  /**
   * <code>repeated .okapi.keys.JsonWebKey key = 1;</code>
   */
  @java.lang.Override
  public trinsic.okapi.keys.JsonWebKeyOrBuilder getKeyOrBuilder(
      int index) {
    return key_.get(index);
  }

  public static final int DID_DOCUMENT_FIELD_NUMBER = 2;
  private com.google.protobuf.Struct didDocument_;
  /**
   * <code>.google.protobuf.Struct did_document = 2;</code>
   * @return Whether the didDocument field is set.
   */
  @java.lang.Override
  public boolean hasDidDocument() {
    return didDocument_ != null;
  }
  /**
   * <code>.google.protobuf.Struct did_document = 2;</code>
   * @return The didDocument.
   */
  @java.lang.Override
  public com.google.protobuf.Struct getDidDocument() {
    return didDocument_ == null ? com.google.protobuf.Struct.getDefaultInstance() : didDocument_;
  }
  /**
   * <code>.google.protobuf.Struct did_document = 2;</code>
   */
  @java.lang.Override
  public com.google.protobuf.StructOrBuilder getDidDocumentOrBuilder() {
    return getDidDocument();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < key_.size(); i++) {
      output.writeMessage(1, key_.get(i));
    }
    if (didDocument_ != null) {
      output.writeMessage(2, getDidDocument());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < key_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, key_.get(i));
    }
    if (didDocument_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getDidDocument());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof trinsic.okapi.keys.GenerateKeyResponse)) {
      return super.equals(obj);
    }
    trinsic.okapi.keys.GenerateKeyResponse other = (trinsic.okapi.keys.GenerateKeyResponse) obj;

    if (!getKeyList()
        .equals(other.getKeyList())) return false;
    if (hasDidDocument() != other.hasDidDocument()) return false;
    if (hasDidDocument()) {
      if (!getDidDocument()
          .equals(other.getDidDocument())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getKeyCount() > 0) {
      hash = (37 * hash) + KEY_FIELD_NUMBER;
      hash = (53 * hash) + getKeyList().hashCode();
    }
    if (hasDidDocument()) {
      hash = (37 * hash) + DID_DOCUMENT_FIELD_NUMBER;
      hash = (53 * hash) + getDidDocument().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static trinsic.okapi.keys.GenerateKeyResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static trinsic.okapi.keys.GenerateKeyResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static trinsic.okapi.keys.GenerateKeyResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static trinsic.okapi.keys.GenerateKeyResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static trinsic.okapi.keys.GenerateKeyResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static trinsic.okapi.keys.GenerateKeyResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static trinsic.okapi.keys.GenerateKeyResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static trinsic.okapi.keys.GenerateKeyResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static trinsic.okapi.keys.GenerateKeyResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static trinsic.okapi.keys.GenerateKeyResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static trinsic.okapi.keys.GenerateKeyResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static trinsic.okapi.keys.GenerateKeyResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(trinsic.okapi.keys.GenerateKeyResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code okapi.keys.GenerateKeyResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:okapi.keys.GenerateKeyResponse)
      trinsic.okapi.keys.GenerateKeyResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return trinsic.okapi.keys.Keys.internal_static_okapi_keys_GenerateKeyResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return trinsic.okapi.keys.Keys.internal_static_okapi_keys_GenerateKeyResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              trinsic.okapi.keys.GenerateKeyResponse.class, trinsic.okapi.keys.GenerateKeyResponse.Builder.class);
    }

    // Construct using trinsic.okapi.keys.GenerateKeyResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getKeyFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (keyBuilder_ == null) {
        key_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        keyBuilder_.clear();
      }
      if (didDocumentBuilder_ == null) {
        didDocument_ = null;
      } else {
        didDocument_ = null;
        didDocumentBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return trinsic.okapi.keys.Keys.internal_static_okapi_keys_GenerateKeyResponse_descriptor;
    }

    @java.lang.Override
    public trinsic.okapi.keys.GenerateKeyResponse getDefaultInstanceForType() {
      return trinsic.okapi.keys.GenerateKeyResponse.getDefaultInstance();
    }

    @java.lang.Override
    public trinsic.okapi.keys.GenerateKeyResponse build() {
      trinsic.okapi.keys.GenerateKeyResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public trinsic.okapi.keys.GenerateKeyResponse buildPartial() {
      trinsic.okapi.keys.GenerateKeyResponse result = new trinsic.okapi.keys.GenerateKeyResponse(this);
      int from_bitField0_ = bitField0_;
      if (keyBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          key_ = java.util.Collections.unmodifiableList(key_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.key_ = key_;
      } else {
        result.key_ = keyBuilder_.build();
      }
      if (didDocumentBuilder_ == null) {
        result.didDocument_ = didDocument_;
      } else {
        result.didDocument_ = didDocumentBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof trinsic.okapi.keys.GenerateKeyResponse) {
        return mergeFrom((trinsic.okapi.keys.GenerateKeyResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(trinsic.okapi.keys.GenerateKeyResponse other) {
      if (other == trinsic.okapi.keys.GenerateKeyResponse.getDefaultInstance()) return this;
      if (keyBuilder_ == null) {
        if (!other.key_.isEmpty()) {
          if (key_.isEmpty()) {
            key_ = other.key_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureKeyIsMutable();
            key_.addAll(other.key_);
          }
          onChanged();
        }
      } else {
        if (!other.key_.isEmpty()) {
          if (keyBuilder_.isEmpty()) {
            keyBuilder_.dispose();
            keyBuilder_ = null;
            key_ = other.key_;
            bitField0_ = (bitField0_ & ~0x00000001);
            keyBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getKeyFieldBuilder() : null;
          } else {
            keyBuilder_.addAllMessages(other.key_);
          }
        }
      }
      if (other.hasDidDocument()) {
        mergeDidDocument(other.getDidDocument());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      trinsic.okapi.keys.GenerateKeyResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (trinsic.okapi.keys.GenerateKeyResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<trinsic.okapi.keys.JsonWebKey> key_ =
      java.util.Collections.emptyList();
    private void ensureKeyIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        key_ = new java.util.ArrayList<trinsic.okapi.keys.JsonWebKey>(key_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        trinsic.okapi.keys.JsonWebKey, trinsic.okapi.keys.JsonWebKey.Builder, trinsic.okapi.keys.JsonWebKeyOrBuilder> keyBuilder_;

    /**
     * <code>repeated .okapi.keys.JsonWebKey key = 1;</code>
     */
    public java.util.List<trinsic.okapi.keys.JsonWebKey> getKeyList() {
      if (keyBuilder_ == null) {
        return java.util.Collections.unmodifiableList(key_);
      } else {
        return keyBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .okapi.keys.JsonWebKey key = 1;</code>
     */
    public int getKeyCount() {
      if (keyBuilder_ == null) {
        return key_.size();
      } else {
        return keyBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .okapi.keys.JsonWebKey key = 1;</code>
     */
    public trinsic.okapi.keys.JsonWebKey getKey(int index) {
      if (keyBuilder_ == null) {
        return key_.get(index);
      } else {
        return keyBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .okapi.keys.JsonWebKey key = 1;</code>
     */
    public Builder setKey(
        int index, trinsic.okapi.keys.JsonWebKey value) {
      if (keyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureKeyIsMutable();
        key_.set(index, value);
        onChanged();
      } else {
        keyBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .okapi.keys.JsonWebKey key = 1;</code>
     */
    public Builder setKey(
        int index, trinsic.okapi.keys.JsonWebKey.Builder builderForValue) {
      if (keyBuilder_ == null) {
        ensureKeyIsMutable();
        key_.set(index, builderForValue.build());
        onChanged();
      } else {
        keyBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .okapi.keys.JsonWebKey key = 1;</code>
     */
    public Builder addKey(trinsic.okapi.keys.JsonWebKey value) {
      if (keyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureKeyIsMutable();
        key_.add(value);
        onChanged();
      } else {
        keyBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .okapi.keys.JsonWebKey key = 1;</code>
     */
    public Builder addKey(
        int index, trinsic.okapi.keys.JsonWebKey value) {
      if (keyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureKeyIsMutable();
        key_.add(index, value);
        onChanged();
      } else {
        keyBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .okapi.keys.JsonWebKey key = 1;</code>
     */
    public Builder addKey(
        trinsic.okapi.keys.JsonWebKey.Builder builderForValue) {
      if (keyBuilder_ == null) {
        ensureKeyIsMutable();
        key_.add(builderForValue.build());
        onChanged();
      } else {
        keyBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .okapi.keys.JsonWebKey key = 1;</code>
     */
    public Builder addKey(
        int index, trinsic.okapi.keys.JsonWebKey.Builder builderForValue) {
      if (keyBuilder_ == null) {
        ensureKeyIsMutable();
        key_.add(index, builderForValue.build());
        onChanged();
      } else {
        keyBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .okapi.keys.JsonWebKey key = 1;</code>
     */
    public Builder addAllKey(
        java.lang.Iterable<? extends trinsic.okapi.keys.JsonWebKey> values) {
      if (keyBuilder_ == null) {
        ensureKeyIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, key_);
        onChanged();
      } else {
        keyBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .okapi.keys.JsonWebKey key = 1;</code>
     */
    public Builder clearKey() {
      if (keyBuilder_ == null) {
        key_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        keyBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .okapi.keys.JsonWebKey key = 1;</code>
     */
    public Builder removeKey(int index) {
      if (keyBuilder_ == null) {
        ensureKeyIsMutable();
        key_.remove(index);
        onChanged();
      } else {
        keyBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .okapi.keys.JsonWebKey key = 1;</code>
     */
    public trinsic.okapi.keys.JsonWebKey.Builder getKeyBuilder(
        int index) {
      return getKeyFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .okapi.keys.JsonWebKey key = 1;</code>
     */
    public trinsic.okapi.keys.JsonWebKeyOrBuilder getKeyOrBuilder(
        int index) {
      if (keyBuilder_ == null) {
        return key_.get(index);  } else {
        return keyBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .okapi.keys.JsonWebKey key = 1;</code>
     */
    public java.util.List<? extends trinsic.okapi.keys.JsonWebKeyOrBuilder> 
         getKeyOrBuilderList() {
      if (keyBuilder_ != null) {
        return keyBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(key_);
      }
    }
    /**
     * <code>repeated .okapi.keys.JsonWebKey key = 1;</code>
     */
    public trinsic.okapi.keys.JsonWebKey.Builder addKeyBuilder() {
      return getKeyFieldBuilder().addBuilder(
          trinsic.okapi.keys.JsonWebKey.getDefaultInstance());
    }
    /**
     * <code>repeated .okapi.keys.JsonWebKey key = 1;</code>
     */
    public trinsic.okapi.keys.JsonWebKey.Builder addKeyBuilder(
        int index) {
      return getKeyFieldBuilder().addBuilder(
          index, trinsic.okapi.keys.JsonWebKey.getDefaultInstance());
    }
    /**
     * <code>repeated .okapi.keys.JsonWebKey key = 1;</code>
     */
    public java.util.List<trinsic.okapi.keys.JsonWebKey.Builder> 
         getKeyBuilderList() {
      return getKeyFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        trinsic.okapi.keys.JsonWebKey, trinsic.okapi.keys.JsonWebKey.Builder, trinsic.okapi.keys.JsonWebKeyOrBuilder> 
        getKeyFieldBuilder() {
      if (keyBuilder_ == null) {
        keyBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            trinsic.okapi.keys.JsonWebKey, trinsic.okapi.keys.JsonWebKey.Builder, trinsic.okapi.keys.JsonWebKeyOrBuilder>(
                key_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        key_ = null;
      }
      return keyBuilder_;
    }

    private com.google.protobuf.Struct didDocument_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> didDocumentBuilder_;
    /**
     * <code>.google.protobuf.Struct did_document = 2;</code>
     * @return Whether the didDocument field is set.
     */
    public boolean hasDidDocument() {
      return didDocumentBuilder_ != null || didDocument_ != null;
    }
    /**
     * <code>.google.protobuf.Struct did_document = 2;</code>
     * @return The didDocument.
     */
    public com.google.protobuf.Struct getDidDocument() {
      if (didDocumentBuilder_ == null) {
        return didDocument_ == null ? com.google.protobuf.Struct.getDefaultInstance() : didDocument_;
      } else {
        return didDocumentBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Struct did_document = 2;</code>
     */
    public Builder setDidDocument(com.google.protobuf.Struct value) {
      if (didDocumentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        didDocument_ = value;
        onChanged();
      } else {
        didDocumentBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Struct did_document = 2;</code>
     */
    public Builder setDidDocument(
        com.google.protobuf.Struct.Builder builderForValue) {
      if (didDocumentBuilder_ == null) {
        didDocument_ = builderForValue.build();
        onChanged();
      } else {
        didDocumentBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Struct did_document = 2;</code>
     */
    public Builder mergeDidDocument(com.google.protobuf.Struct value) {
      if (didDocumentBuilder_ == null) {
        if (didDocument_ != null) {
          didDocument_ =
            com.google.protobuf.Struct.newBuilder(didDocument_).mergeFrom(value).buildPartial();
        } else {
          didDocument_ = value;
        }
        onChanged();
      } else {
        didDocumentBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Struct did_document = 2;</code>
     */
    public Builder clearDidDocument() {
      if (didDocumentBuilder_ == null) {
        didDocument_ = null;
        onChanged();
      } else {
        didDocument_ = null;
        didDocumentBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Struct did_document = 2;</code>
     */
    public com.google.protobuf.Struct.Builder getDidDocumentBuilder() {
      
      onChanged();
      return getDidDocumentFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Struct did_document = 2;</code>
     */
    public com.google.protobuf.StructOrBuilder getDidDocumentOrBuilder() {
      if (didDocumentBuilder_ != null) {
        return didDocumentBuilder_.getMessageOrBuilder();
      } else {
        return didDocument_ == null ?
            com.google.protobuf.Struct.getDefaultInstance() : didDocument_;
      }
    }
    /**
     * <code>.google.protobuf.Struct did_document = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> 
        getDidDocumentFieldBuilder() {
      if (didDocumentBuilder_ == null) {
        didDocumentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder>(
                getDidDocument(),
                getParentForChildren(),
                isClean());
        didDocument_ = null;
      }
      return didDocumentBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:okapi.keys.GenerateKeyResponse)
  }

  // @@protoc_insertion_point(class_scope:okapi.keys.GenerateKeyResponse)
  private static final trinsic.okapi.keys.GenerateKeyResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new trinsic.okapi.keys.GenerateKeyResponse();
  }

  public static trinsic.okapi.keys.GenerateKeyResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GenerateKeyResponse>
      PARSER = new com.google.protobuf.AbstractParser<GenerateKeyResponse>() {
    @java.lang.Override
    public GenerateKeyResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GenerateKeyResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GenerateKeyResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GenerateKeyResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public trinsic.okapi.keys.GenerateKeyResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

