source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '12.0'

install! 'cocoapods', :deterministic_uuids => false

target 'Okapi-Example' do
  # Depend on the generated HelloWorld library.
  pod 'Okapi-iOS', :path => '../../'
end