source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '12.0'

install! 'cocoapods', :deterministic_uuids => false

target 'DIDComm-gRPC-Example' do
  # Depend on the generated HelloWorld library.
  pod 'DIDComm-gRPC', :path => '../../'
end