// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: security.proto

package trinsic.okapi.security;

public interface BlindOberonTokenResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:okapi.security.BlindOberonTokenResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * raw blinded token bytes
   * </pre>
   *
   * <code>bytes token = 1;</code>
   * @return The token.
   */
  com.google.protobuf.ByteString getToken();
}
