// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: security.proto

package trinsic.okapi.security;

/**
 * <pre>
 * Verify the presented proof is valid
 * </pre>
 *
 * Protobuf type {@code okapi.security.VerifyOberonProofRequest}
 */
public final class VerifyOberonProofRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:okapi.security.VerifyOberonProofRequest)
    VerifyOberonProofRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use VerifyOberonProofRequest.newBuilder() to construct.
  private VerifyOberonProofRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private VerifyOberonProofRequest() {
    proof_ = com.google.protobuf.ByteString.EMPTY;
    data_ = com.google.protobuf.ByteString.EMPTY;
    nonce_ = com.google.protobuf.ByteString.EMPTY;
    pk_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new VerifyOberonProofRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private VerifyOberonProofRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {

            proof_ = input.readBytes();
            break;
          }
          case 18: {

            data_ = input.readBytes();
            break;
          }
          case 26: {

            nonce_ = input.readBytes();
            break;
          }
          case 34: {

            pk_ = input.readBytes();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return trinsic.okapi.security.Security.internal_static_okapi_security_VerifyOberonProofRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return trinsic.okapi.security.Security.internal_static_okapi_security_VerifyOberonProofRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            trinsic.okapi.security.VerifyOberonProofRequest.class, trinsic.okapi.security.VerifyOberonProofRequest.Builder.class);
  }

  public static final int PROOF_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString proof_;
  /**
   * <pre>
   * raw proof bytes returned from CreateProof
   * </pre>
   *
   * <code>bytes proof = 1;</code>
   * @return The proof.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getProof() {
    return proof_;
  }

  public static final int DATA_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString data_;
  /**
   * <pre>
   * data used to create the token
   * </pre>
   *
   * <code>bytes data = 2;</code>
   * @return The data.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getData() {
    return data_;
  }

  public static final int NONCE_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString nonce_;
  /**
   * <pre>
   * nonce used to generate the proof
   * </pre>
   *
   * <code>bytes nonce = 3;</code>
   * @return The nonce.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getNonce() {
    return nonce_;
  }

  public static final int PK_FIELD_NUMBER = 4;
  private com.google.protobuf.ByteString pk_;
  /**
   * <pre>
   * public key that was used to generate the token
   * </pre>
   *
   * <code>bytes pk = 4;</code>
   * @return The pk.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getPk() {
    return pk_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!proof_.isEmpty()) {
      output.writeBytes(1, proof_);
    }
    if (!data_.isEmpty()) {
      output.writeBytes(2, data_);
    }
    if (!nonce_.isEmpty()) {
      output.writeBytes(3, nonce_);
    }
    if (!pk_.isEmpty()) {
      output.writeBytes(4, pk_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!proof_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, proof_);
    }
    if (!data_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, data_);
    }
    if (!nonce_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, nonce_);
    }
    if (!pk_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(4, pk_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof trinsic.okapi.security.VerifyOberonProofRequest)) {
      return super.equals(obj);
    }
    trinsic.okapi.security.VerifyOberonProofRequest other = (trinsic.okapi.security.VerifyOberonProofRequest) obj;

    if (!getProof()
        .equals(other.getProof())) return false;
    if (!getData()
        .equals(other.getData())) return false;
    if (!getNonce()
        .equals(other.getNonce())) return false;
    if (!getPk()
        .equals(other.getPk())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PROOF_FIELD_NUMBER;
    hash = (53 * hash) + getProof().hashCode();
    hash = (37 * hash) + DATA_FIELD_NUMBER;
    hash = (53 * hash) + getData().hashCode();
    hash = (37 * hash) + NONCE_FIELD_NUMBER;
    hash = (53 * hash) + getNonce().hashCode();
    hash = (37 * hash) + PK_FIELD_NUMBER;
    hash = (53 * hash) + getPk().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static trinsic.okapi.security.VerifyOberonProofRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static trinsic.okapi.security.VerifyOberonProofRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static trinsic.okapi.security.VerifyOberonProofRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static trinsic.okapi.security.VerifyOberonProofRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static trinsic.okapi.security.VerifyOberonProofRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static trinsic.okapi.security.VerifyOberonProofRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static trinsic.okapi.security.VerifyOberonProofRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static trinsic.okapi.security.VerifyOberonProofRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static trinsic.okapi.security.VerifyOberonProofRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static trinsic.okapi.security.VerifyOberonProofRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static trinsic.okapi.security.VerifyOberonProofRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static trinsic.okapi.security.VerifyOberonProofRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(trinsic.okapi.security.VerifyOberonProofRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Verify the presented proof is valid
   * </pre>
   *
   * Protobuf type {@code okapi.security.VerifyOberonProofRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:okapi.security.VerifyOberonProofRequest)
      trinsic.okapi.security.VerifyOberonProofRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return trinsic.okapi.security.Security.internal_static_okapi_security_VerifyOberonProofRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return trinsic.okapi.security.Security.internal_static_okapi_security_VerifyOberonProofRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              trinsic.okapi.security.VerifyOberonProofRequest.class, trinsic.okapi.security.VerifyOberonProofRequest.Builder.class);
    }

    // Construct using trinsic.okapi.security.VerifyOberonProofRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      proof_ = com.google.protobuf.ByteString.EMPTY;

      data_ = com.google.protobuf.ByteString.EMPTY;

      nonce_ = com.google.protobuf.ByteString.EMPTY;

      pk_ = com.google.protobuf.ByteString.EMPTY;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return trinsic.okapi.security.Security.internal_static_okapi_security_VerifyOberonProofRequest_descriptor;
    }

    @java.lang.Override
    public trinsic.okapi.security.VerifyOberonProofRequest getDefaultInstanceForType() {
      return trinsic.okapi.security.VerifyOberonProofRequest.getDefaultInstance();
    }

    @java.lang.Override
    public trinsic.okapi.security.VerifyOberonProofRequest build() {
      trinsic.okapi.security.VerifyOberonProofRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public trinsic.okapi.security.VerifyOberonProofRequest buildPartial() {
      trinsic.okapi.security.VerifyOberonProofRequest result = new trinsic.okapi.security.VerifyOberonProofRequest(this);
      result.proof_ = proof_;
      result.data_ = data_;
      result.nonce_ = nonce_;
      result.pk_ = pk_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof trinsic.okapi.security.VerifyOberonProofRequest) {
        return mergeFrom((trinsic.okapi.security.VerifyOberonProofRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(trinsic.okapi.security.VerifyOberonProofRequest other) {
      if (other == trinsic.okapi.security.VerifyOberonProofRequest.getDefaultInstance()) return this;
      if (other.getProof() != com.google.protobuf.ByteString.EMPTY) {
        setProof(other.getProof());
      }
      if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
        setData(other.getData());
      }
      if (other.getNonce() != com.google.protobuf.ByteString.EMPTY) {
        setNonce(other.getNonce());
      }
      if (other.getPk() != com.google.protobuf.ByteString.EMPTY) {
        setPk(other.getPk());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      trinsic.okapi.security.VerifyOberonProofRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (trinsic.okapi.security.VerifyOberonProofRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.protobuf.ByteString proof_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * raw proof bytes returned from CreateProof
     * </pre>
     *
     * <code>bytes proof = 1;</code>
     * @return The proof.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getProof() {
      return proof_;
    }
    /**
     * <pre>
     * raw proof bytes returned from CreateProof
     * </pre>
     *
     * <code>bytes proof = 1;</code>
     * @param value The proof to set.
     * @return This builder for chaining.
     */
    public Builder setProof(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      proof_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * raw proof bytes returned from CreateProof
     * </pre>
     *
     * <code>bytes proof = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearProof() {
      
      proof_ = getDefaultInstance().getProof();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * data used to create the token
     * </pre>
     *
     * <code>bytes data = 2;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }
    /**
     * <pre>
     * data used to create the token
     * </pre>
     *
     * <code>bytes data = 2;</code>
     * @param value The data to set.
     * @return This builder for chaining.
     */
    public Builder setData(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      data_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * data used to create the token
     * </pre>
     *
     * <code>bytes data = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearData() {
      
      data_ = getDefaultInstance().getData();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString nonce_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * nonce used to generate the proof
     * </pre>
     *
     * <code>bytes nonce = 3;</code>
     * @return The nonce.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getNonce() {
      return nonce_;
    }
    /**
     * <pre>
     * nonce used to generate the proof
     * </pre>
     *
     * <code>bytes nonce = 3;</code>
     * @param value The nonce to set.
     * @return This builder for chaining.
     */
    public Builder setNonce(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      nonce_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * nonce used to generate the proof
     * </pre>
     *
     * <code>bytes nonce = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearNonce() {
      
      nonce_ = getDefaultInstance().getNonce();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString pk_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * public key that was used to generate the token
     * </pre>
     *
     * <code>bytes pk = 4;</code>
     * @return The pk.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPk() {
      return pk_;
    }
    /**
     * <pre>
     * public key that was used to generate the token
     * </pre>
     *
     * <code>bytes pk = 4;</code>
     * @param value The pk to set.
     * @return This builder for chaining.
     */
    public Builder setPk(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      pk_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * public key that was used to generate the token
     * </pre>
     *
     * <code>bytes pk = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPk() {
      
      pk_ = getDefaultInstance().getPk();
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:okapi.security.VerifyOberonProofRequest)
  }

  // @@protoc_insertion_point(class_scope:okapi.security.VerifyOberonProofRequest)
  private static final trinsic.okapi.security.VerifyOberonProofRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new trinsic.okapi.security.VerifyOberonProofRequest();
  }

  public static trinsic.okapi.security.VerifyOberonProofRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<VerifyOberonProofRequest>
      PARSER = new com.google.protobuf.AbstractParser<VerifyOberonProofRequest>() {
    @java.lang.Override
    public VerifyOberonProofRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new VerifyOberonProofRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<VerifyOberonProofRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<VerifyOberonProofRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public trinsic.okapi.security.VerifyOberonProofRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

