project 'okapi.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'okapi' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
  pod 'Protobuf'

  # Pods for okapi

  target 'okapiTests' do
    # Pods for testing
  end

end
