//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: okapi/keys/v1/keys.proto

package trinsic.okapi.keys.v1;

@kotlin.jvm.JvmName("-initializegenerateKeyResponse")
public inline fun generateKeyResponse(block: trinsic.okapi.keys.v1.GenerateKeyResponseKt.Dsl.() -> kotlin.Unit): trinsic.okapi.keys.v1.Keys.GenerateKeyResponse =
  trinsic.okapi.keys.v1.GenerateKeyResponseKt.Dsl._create(trinsic.okapi.keys.v1.Keys.GenerateKeyResponse.newBuilder()).apply { block() }._build()
public object GenerateKeyResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: trinsic.okapi.keys.v1.Keys.GenerateKeyResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: trinsic.okapi.keys.v1.Keys.GenerateKeyResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): trinsic.okapi.keys.v1.Keys.GenerateKeyResponse = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class KeyProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .okapi.keys.v1.JsonWebKey key = 1;</code>
     */
     public val key: com.google.protobuf.kotlin.DslList<trinsic.okapi.keys.v1.Keys.JsonWebKey, KeyProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getKeyList()
      )
    /**
     * <code>repeated .okapi.keys.v1.JsonWebKey key = 1;</code>
     * @param value The key to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addKey")
    public fun com.google.protobuf.kotlin.DslList<trinsic.okapi.keys.v1.Keys.JsonWebKey, KeyProxy>.add(value: trinsic.okapi.keys.v1.Keys.JsonWebKey) {
      _builder.addKey(value)
    }
    /**
     * <code>repeated .okapi.keys.v1.JsonWebKey key = 1;</code>
     * @param value The key to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignKey")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<trinsic.okapi.keys.v1.Keys.JsonWebKey, KeyProxy>.plusAssign(value: trinsic.okapi.keys.v1.Keys.JsonWebKey) {
      add(value)
    }
    /**
     * <code>repeated .okapi.keys.v1.JsonWebKey key = 1;</code>
     * @param values The key to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllKey")
    public fun com.google.protobuf.kotlin.DslList<trinsic.okapi.keys.v1.Keys.JsonWebKey, KeyProxy>.addAll(values: kotlin.collections.Iterable<trinsic.okapi.keys.v1.Keys.JsonWebKey>) {
      _builder.addAllKey(values)
    }
    /**
     * <code>repeated .okapi.keys.v1.JsonWebKey key = 1;</code>
     * @param values The key to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllKey")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<trinsic.okapi.keys.v1.Keys.JsonWebKey, KeyProxy>.plusAssign(values: kotlin.collections.Iterable<trinsic.okapi.keys.v1.Keys.JsonWebKey>) {
      addAll(values)
    }
    /**
     * <code>repeated .okapi.keys.v1.JsonWebKey key = 1;</code>
     * @param index The index to set the value at.
     * @param value The key to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setKey")
    public operator fun com.google.protobuf.kotlin.DslList<trinsic.okapi.keys.v1.Keys.JsonWebKey, KeyProxy>.set(index: kotlin.Int, value: trinsic.okapi.keys.v1.Keys.JsonWebKey) {
      _builder.setKey(index, value)
    }
    /**
     * <code>repeated .okapi.keys.v1.JsonWebKey key = 1;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearKey")
    public fun com.google.protobuf.kotlin.DslList<trinsic.okapi.keys.v1.Keys.JsonWebKey, KeyProxy>.clear() {
      _builder.clearKey()
    }


    /**
     * <code>.google.protobuf.Struct did_document = 2;</code>
     */
    public var didDocument: com.google.protobuf.Struct
      @JvmName("getDidDocument")
      get() = _builder.getDidDocument()
      @JvmName("setDidDocument")
      set(value) {
        _builder.setDidDocument(value)
      }
    /**
     * <code>.google.protobuf.Struct did_document = 2;</code>
     */
    public fun clearDidDocument() {
      _builder.clearDidDocument()
    }
    /**
     * <code>.google.protobuf.Struct did_document = 2;</code>
     * @return Whether the didDocument field is set.
     */
    public fun hasDidDocument(): kotlin.Boolean {
      return _builder.hasDidDocument()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun trinsic.okapi.keys.v1.Keys.GenerateKeyResponse.copy(block: trinsic.okapi.keys.v1.GenerateKeyResponseKt.Dsl.() -> kotlin.Unit): trinsic.okapi.keys.v1.Keys.GenerateKeyResponse =
  trinsic.okapi.keys.v1.GenerateKeyResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

val trinsic.okapi.keys.v1.Keys.GenerateKeyResponseOrBuilder.didDocumentOrNull: com.google.protobuf.Struct?
  get() = if (hasDidDocument()) getDidDocument() else null

