//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: okapi/keys/v1/keys.proto

package trinsic.okapi.keys.v1;

@kotlin.jvm.JvmSynthetic
inline fun jsonWebKey(block: trinsic.okapi.keys.v1.JsonWebKeyKt.Dsl.() -> Unit): trinsic.okapi.keys.v1.Keys.JsonWebKey =
  trinsic.okapi.keys.v1.JsonWebKeyKt.Dsl._create(trinsic.okapi.keys.v1.Keys.JsonWebKey.newBuilder()).apply { block() }._build()
object JsonWebKeyKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: trinsic.okapi.keys.v1.Keys.JsonWebKey.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: trinsic.okapi.keys.v1.Keys.JsonWebKey.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): trinsic.okapi.keys.v1.Keys.JsonWebKey = _builder.build()

    /**
     * <code>string kid = 1;</code>
     */
    var kid: kotlin.String
      @JvmName("getKid")
      get() = _builder.getKid()
      @JvmName("setKid")
      set(value) {
        _builder.setKid(value)
      }
    /**
     * <code>string kid = 1;</code>
     */
    fun clearKid() {
      _builder.clearKid()
    }

    /**
     * <pre>
     * public_key
     * </pre>
     *
     * <code>string x = 2;</code>
     */
    var x: kotlin.String
      @JvmName("getX")
      get() = _builder.getX()
      @JvmName("setX")
      set(value) {
        _builder.setX(value)
      }
    /**
     * <pre>
     * public_key
     * </pre>
     *
     * <code>string x = 2;</code>
     */
    fun clearX() {
      _builder.clearX()
    }

    /**
     * <pre>
     * public_key
     * </pre>
     *
     * <code>string y = 3;</code>
     */
    var y: kotlin.String
      @JvmName("getY")
      get() = _builder.getY()
      @JvmName("setY")
      set(value) {
        _builder.setY(value)
      }
    /**
     * <pre>
     * public_key
     * </pre>
     *
     * <code>string y = 3;</code>
     */
    fun clearY() {
      _builder.clearY()
    }

    /**
     * <pre>
     * secret_key
     * </pre>
     *
     * <code>string d = 4;</code>
     */
    var d: kotlin.String
      @JvmName("getD")
      get() = _builder.getD()
      @JvmName("setD")
      set(value) {
        _builder.setD(value)
      }
    /**
     * <pre>
     * secret_key
     * </pre>
     *
     * <code>string d = 4;</code>
     */
    fun clearD() {
      _builder.clearD()
    }

    /**
     * <code>string crv = 5;</code>
     */
    var crv: kotlin.String
      @JvmName("getCrv")
      get() = _builder.getCrv()
      @JvmName("setCrv")
      set(value) {
        _builder.setCrv(value)
      }
    /**
     * <code>string crv = 5;</code>
     */
    fun clearCrv() {
      _builder.clearCrv()
    }

    /**
     * <code>string kty = 6;</code>
     */
    var kty: kotlin.String
      @JvmName("getKty")
      get() = _builder.getKty()
      @JvmName("setKty")
      set(value) {
        _builder.setKty(value)
      }
    /**
     * <code>string kty = 6;</code>
     */
    fun clearKty() {
      _builder.clearKty()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun trinsic.okapi.keys.v1.Keys.JsonWebKey.copy(block: trinsic.okapi.keys.v1.JsonWebKeyKt.Dsl.() -> Unit): trinsic.okapi.keys.v1.Keys.JsonWebKey =
  trinsic.okapi.keys.v1.JsonWebKeyKt.Dsl._create(this.toBuilder()).apply { block() }._build()
