// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: okapi/keys/v1/keys.proto

package trinsic.okapi.keys.v1

@kotlin.jvm.JvmName("-initializejsonWebKey")
public inline fun jsonWebKey(
    block: trinsic.okapi.keys.v1.JsonWebKeyKt.Dsl.() -> kotlin.Unit
): trinsic.okapi.keys.v1.Keys.JsonWebKey =
    trinsic.okapi.keys.v1.JsonWebKeyKt.Dsl._create(
            trinsic.okapi.keys.v1.Keys.JsonWebKey.newBuilder())
        .apply { block() }
        ._build()

public object JsonWebKeyKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl
  private constructor(private val _builder: trinsic.okapi.keys.v1.Keys.JsonWebKey.Builder) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: trinsic.okapi.keys.v1.Keys.JsonWebKey.Builder): Dsl =
          Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): trinsic.okapi.keys.v1.Keys.JsonWebKey = _builder.build()

    /** <code>string kid = 1;</code> */
    public var kid: kotlin.String
      @JvmName("getKid") get() = _builder.getKid()
      @JvmName("setKid")
      set(value) {
        _builder.setKid(value)
      }
    /** <code>string kid = 1;</code> */
    public fun clearKid() {
      _builder.clearKid()
    }

    /**
     * <pre> public_key </pre>
     *
     * <code>string x = 2;</code>
     */
    public var x: kotlin.String
      @JvmName("getX") get() = _builder.getX()
      @JvmName("setX")
      set(value) {
        _builder.setX(value)
      }
    /**
     * <pre> public_key </pre>
     *
     * <code>string x = 2;</code>
     */
    public fun clearX() {
      _builder.clearX()
    }

    /**
     * <pre> public_key </pre>
     *
     * <code>string y = 3;</code>
     */
    public var y: kotlin.String
      @JvmName("getY") get() = _builder.getY()
      @JvmName("setY")
      set(value) {
        _builder.setY(value)
      }
    /**
     * <pre> public_key </pre>
     *
     * <code>string y = 3;</code>
     */
    public fun clearY() {
      _builder.clearY()
    }

    /**
     * <pre> secret_key </pre>
     *
     * <code>string d = 4;</code>
     */
    public var d: kotlin.String
      @JvmName("getD") get() = _builder.getD()
      @JvmName("setD")
      set(value) {
        _builder.setD(value)
      }
    /**
     * <pre> secret_key </pre>
     *
     * <code>string d = 4;</code>
     */
    public fun clearD() {
      _builder.clearD()
    }

    /** <code>string crv = 5;</code> */
    public var crv: kotlin.String
      @JvmName("getCrv") get() = _builder.getCrv()
      @JvmName("setCrv")
      set(value) {
        _builder.setCrv(value)
      }
    /** <code>string crv = 5;</code> */
    public fun clearCrv() {
      _builder.clearCrv()
    }

    /** <code>string kty = 6;</code> */
    public var kty: kotlin.String
      @JvmName("getKty") get() = _builder.getKty()
      @JvmName("setKty")
      set(value) {
        _builder.setKty(value)
      }
    /** <code>string kty = 6;</code> */
    public fun clearKty() {
      _builder.clearKty()
    }
  }
}

@kotlin.jvm.JvmSynthetic
public inline fun trinsic.okapi.keys.v1.Keys.JsonWebKey.copy(
    block: trinsic.okapi.keys.v1.JsonWebKeyKt.Dsl.() -> kotlin.Unit
): trinsic.okapi.keys.v1.Keys.JsonWebKey =
    trinsic.okapi.keys.v1.JsonWebKeyKt.Dsl._create(this.toBuilder()).apply { block() }._build()
