# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: examples.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto
from betterproto.grpc.grpclib_server import ServiceBase


@dataclass(eq=False, repr=False)
class BasicMessage(betterproto.Message):
    text: str = betterproto.string_field(1)
