// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pbmse/pbmse.proto

package trinsic.okapi.pbmse;

/**
 * Protobuf type {@code pbmse.EncryptedMessage}
 */
public final class EncryptedMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:pbmse.EncryptedMessage)
    EncryptedMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EncryptedMessage.newBuilder() to construct.
  private EncryptedMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EncryptedMessage() {
    iv_ = com.google.protobuf.ByteString.EMPTY;
    aad_ = com.google.protobuf.ByteString.EMPTY;
    ciphertext_ = com.google.protobuf.ByteString.EMPTY;
    tag_ = com.google.protobuf.ByteString.EMPTY;
    recipients_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new EncryptedMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private EncryptedMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {

            iv_ = input.readBytes();
            break;
          }
          case 18: {

            aad_ = input.readBytes();
            break;
          }
          case 26: {

            ciphertext_ = input.readBytes();
            break;
          }
          case 34: {

            tag_ = input.readBytes();
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              recipients_ = new java.util.ArrayList<trinsic.okapi.pbmse.EncryptionRecipient>();
              mutable_bitField0_ |= 0x00000001;
            }
            recipients_.add(
                input.readMessage(trinsic.okapi.pbmse.EncryptionRecipient.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        recipients_ = java.util.Collections.unmodifiableList(recipients_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return trinsic.okapi.pbmse.Pbmse.internal_static_pbmse_EncryptedMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return trinsic.okapi.pbmse.Pbmse.internal_static_pbmse_EncryptedMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            trinsic.okapi.pbmse.EncryptedMessage.class, trinsic.okapi.pbmse.EncryptedMessage.Builder.class);
  }

  public static final int IV_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString iv_;
  /**
   * <code>bytes iv = 1 [json_name = "iv"];</code>
   * @return The iv.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getIv() {
    return iv_;
  }

  public static final int AAD_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString aad_;
  /**
   * <code>bytes aad = 2 [json_name = "aad"];</code>
   * @return The aad.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getAad() {
    return aad_;
  }

  public static final int CIPHERTEXT_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString ciphertext_;
  /**
   * <code>bytes ciphertext = 3 [json_name = "ciphertext"];</code>
   * @return The ciphertext.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getCiphertext() {
    return ciphertext_;
  }

  public static final int TAG_FIELD_NUMBER = 4;
  private com.google.protobuf.ByteString tag_;
  /**
   * <code>bytes tag = 4;</code>
   * @return The tag.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getTag() {
    return tag_;
  }

  public static final int RECIPIENTS_FIELD_NUMBER = 5;
  private java.util.List<trinsic.okapi.pbmse.EncryptionRecipient> recipients_;
  /**
   * <code>repeated .pbmse.EncryptionRecipient recipients = 5;</code>
   */
  @java.lang.Override
  public java.util.List<trinsic.okapi.pbmse.EncryptionRecipient> getRecipientsList() {
    return recipients_;
  }
  /**
   * <code>repeated .pbmse.EncryptionRecipient recipients = 5;</code>
   */
  @java.lang.Override
  public java.util.List<? extends trinsic.okapi.pbmse.EncryptionRecipientOrBuilder> 
      getRecipientsOrBuilderList() {
    return recipients_;
  }
  /**
   * <code>repeated .pbmse.EncryptionRecipient recipients = 5;</code>
   */
  @java.lang.Override
  public int getRecipientsCount() {
    return recipients_.size();
  }
  /**
   * <code>repeated .pbmse.EncryptionRecipient recipients = 5;</code>
   */
  @java.lang.Override
  public trinsic.okapi.pbmse.EncryptionRecipient getRecipients(int index) {
    return recipients_.get(index);
  }
  /**
   * <code>repeated .pbmse.EncryptionRecipient recipients = 5;</code>
   */
  @java.lang.Override
  public trinsic.okapi.pbmse.EncryptionRecipientOrBuilder getRecipientsOrBuilder(
      int index) {
    return recipients_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!iv_.isEmpty()) {
      output.writeBytes(1, iv_);
    }
    if (!aad_.isEmpty()) {
      output.writeBytes(2, aad_);
    }
    if (!ciphertext_.isEmpty()) {
      output.writeBytes(3, ciphertext_);
    }
    if (!tag_.isEmpty()) {
      output.writeBytes(4, tag_);
    }
    for (int i = 0; i < recipients_.size(); i++) {
      output.writeMessage(5, recipients_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!iv_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, iv_);
    }
    if (!aad_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, aad_);
    }
    if (!ciphertext_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, ciphertext_);
    }
    if (!tag_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(4, tag_);
    }
    for (int i = 0; i < recipients_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, recipients_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof trinsic.okapi.pbmse.EncryptedMessage)) {
      return super.equals(obj);
    }
    trinsic.okapi.pbmse.EncryptedMessage other = (trinsic.okapi.pbmse.EncryptedMessage) obj;

    if (!getIv()
        .equals(other.getIv())) return false;
    if (!getAad()
        .equals(other.getAad())) return false;
    if (!getCiphertext()
        .equals(other.getCiphertext())) return false;
    if (!getTag()
        .equals(other.getTag())) return false;
    if (!getRecipientsList()
        .equals(other.getRecipientsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + IV_FIELD_NUMBER;
    hash = (53 * hash) + getIv().hashCode();
    hash = (37 * hash) + AAD_FIELD_NUMBER;
    hash = (53 * hash) + getAad().hashCode();
    hash = (37 * hash) + CIPHERTEXT_FIELD_NUMBER;
    hash = (53 * hash) + getCiphertext().hashCode();
    hash = (37 * hash) + TAG_FIELD_NUMBER;
    hash = (53 * hash) + getTag().hashCode();
    if (getRecipientsCount() > 0) {
      hash = (37 * hash) + RECIPIENTS_FIELD_NUMBER;
      hash = (53 * hash) + getRecipientsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static trinsic.okapi.pbmse.EncryptedMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static trinsic.okapi.pbmse.EncryptedMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static trinsic.okapi.pbmse.EncryptedMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static trinsic.okapi.pbmse.EncryptedMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static trinsic.okapi.pbmse.EncryptedMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static trinsic.okapi.pbmse.EncryptedMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static trinsic.okapi.pbmse.EncryptedMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static trinsic.okapi.pbmse.EncryptedMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static trinsic.okapi.pbmse.EncryptedMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static trinsic.okapi.pbmse.EncryptedMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static trinsic.okapi.pbmse.EncryptedMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static trinsic.okapi.pbmse.EncryptedMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(trinsic.okapi.pbmse.EncryptedMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code pbmse.EncryptedMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:pbmse.EncryptedMessage)
      trinsic.okapi.pbmse.EncryptedMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return trinsic.okapi.pbmse.Pbmse.internal_static_pbmse_EncryptedMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return trinsic.okapi.pbmse.Pbmse.internal_static_pbmse_EncryptedMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              trinsic.okapi.pbmse.EncryptedMessage.class, trinsic.okapi.pbmse.EncryptedMessage.Builder.class);
    }

    // Construct using trinsic.okapi.pbmse.EncryptedMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getRecipientsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      iv_ = com.google.protobuf.ByteString.EMPTY;

      aad_ = com.google.protobuf.ByteString.EMPTY;

      ciphertext_ = com.google.protobuf.ByteString.EMPTY;

      tag_ = com.google.protobuf.ByteString.EMPTY;

      if (recipientsBuilder_ == null) {
        recipients_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        recipientsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return trinsic.okapi.pbmse.Pbmse.internal_static_pbmse_EncryptedMessage_descriptor;
    }

    @java.lang.Override
    public trinsic.okapi.pbmse.EncryptedMessage getDefaultInstanceForType() {
      return trinsic.okapi.pbmse.EncryptedMessage.getDefaultInstance();
    }

    @java.lang.Override
    public trinsic.okapi.pbmse.EncryptedMessage build() {
      trinsic.okapi.pbmse.EncryptedMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public trinsic.okapi.pbmse.EncryptedMessage buildPartial() {
      trinsic.okapi.pbmse.EncryptedMessage result = new trinsic.okapi.pbmse.EncryptedMessage(this);
      int from_bitField0_ = bitField0_;
      result.iv_ = iv_;
      result.aad_ = aad_;
      result.ciphertext_ = ciphertext_;
      result.tag_ = tag_;
      if (recipientsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          recipients_ = java.util.Collections.unmodifiableList(recipients_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.recipients_ = recipients_;
      } else {
        result.recipients_ = recipientsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof trinsic.okapi.pbmse.EncryptedMessage) {
        return mergeFrom((trinsic.okapi.pbmse.EncryptedMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(trinsic.okapi.pbmse.EncryptedMessage other) {
      if (other == trinsic.okapi.pbmse.EncryptedMessage.getDefaultInstance()) return this;
      if (other.getIv() != com.google.protobuf.ByteString.EMPTY) {
        setIv(other.getIv());
      }
      if (other.getAad() != com.google.protobuf.ByteString.EMPTY) {
        setAad(other.getAad());
      }
      if (other.getCiphertext() != com.google.protobuf.ByteString.EMPTY) {
        setCiphertext(other.getCiphertext());
      }
      if (other.getTag() != com.google.protobuf.ByteString.EMPTY) {
        setTag(other.getTag());
      }
      if (recipientsBuilder_ == null) {
        if (!other.recipients_.isEmpty()) {
          if (recipients_.isEmpty()) {
            recipients_ = other.recipients_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRecipientsIsMutable();
            recipients_.addAll(other.recipients_);
          }
          onChanged();
        }
      } else {
        if (!other.recipients_.isEmpty()) {
          if (recipientsBuilder_.isEmpty()) {
            recipientsBuilder_.dispose();
            recipientsBuilder_ = null;
            recipients_ = other.recipients_;
            bitField0_ = (bitField0_ & ~0x00000001);
            recipientsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getRecipientsFieldBuilder() : null;
          } else {
            recipientsBuilder_.addAllMessages(other.recipients_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      trinsic.okapi.pbmse.EncryptedMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (trinsic.okapi.pbmse.EncryptedMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.ByteString iv_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes iv = 1 [json_name = "iv"];</code>
     * @return The iv.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getIv() {
      return iv_;
    }
    /**
     * <code>bytes iv = 1 [json_name = "iv"];</code>
     * @param value The iv to set.
     * @return This builder for chaining.
     */
    public Builder setIv(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      iv_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes iv = 1 [json_name = "iv"];</code>
     * @return This builder for chaining.
     */
    public Builder clearIv() {
      
      iv_ = getDefaultInstance().getIv();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString aad_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes aad = 2 [json_name = "aad"];</code>
     * @return The aad.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getAad() {
      return aad_;
    }
    /**
     * <code>bytes aad = 2 [json_name = "aad"];</code>
     * @param value The aad to set.
     * @return This builder for chaining.
     */
    public Builder setAad(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      aad_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes aad = 2 [json_name = "aad"];</code>
     * @return This builder for chaining.
     */
    public Builder clearAad() {
      
      aad_ = getDefaultInstance().getAad();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString ciphertext_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes ciphertext = 3 [json_name = "ciphertext"];</code>
     * @return The ciphertext.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getCiphertext() {
      return ciphertext_;
    }
    /**
     * <code>bytes ciphertext = 3 [json_name = "ciphertext"];</code>
     * @param value The ciphertext to set.
     * @return This builder for chaining.
     */
    public Builder setCiphertext(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ciphertext_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes ciphertext = 3 [json_name = "ciphertext"];</code>
     * @return This builder for chaining.
     */
    public Builder clearCiphertext() {
      
      ciphertext_ = getDefaultInstance().getCiphertext();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString tag_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes tag = 4;</code>
     * @return The tag.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getTag() {
      return tag_;
    }
    /**
     * <code>bytes tag = 4;</code>
     * @param value The tag to set.
     * @return This builder for chaining.
     */
    public Builder setTag(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      tag_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes tag = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTag() {
      
      tag_ = getDefaultInstance().getTag();
      onChanged();
      return this;
    }

    private java.util.List<trinsic.okapi.pbmse.EncryptionRecipient> recipients_ =
      java.util.Collections.emptyList();
    private void ensureRecipientsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        recipients_ = new java.util.ArrayList<trinsic.okapi.pbmse.EncryptionRecipient>(recipients_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        trinsic.okapi.pbmse.EncryptionRecipient, trinsic.okapi.pbmse.EncryptionRecipient.Builder, trinsic.okapi.pbmse.EncryptionRecipientOrBuilder> recipientsBuilder_;

    /**
     * <code>repeated .pbmse.EncryptionRecipient recipients = 5;</code>
     */
    public java.util.List<trinsic.okapi.pbmse.EncryptionRecipient> getRecipientsList() {
      if (recipientsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(recipients_);
      } else {
        return recipientsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .pbmse.EncryptionRecipient recipients = 5;</code>
     */
    public int getRecipientsCount() {
      if (recipientsBuilder_ == null) {
        return recipients_.size();
      } else {
        return recipientsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .pbmse.EncryptionRecipient recipients = 5;</code>
     */
    public trinsic.okapi.pbmse.EncryptionRecipient getRecipients(int index) {
      if (recipientsBuilder_ == null) {
        return recipients_.get(index);
      } else {
        return recipientsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .pbmse.EncryptionRecipient recipients = 5;</code>
     */
    public Builder setRecipients(
        int index, trinsic.okapi.pbmse.EncryptionRecipient value) {
      if (recipientsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRecipientsIsMutable();
        recipients_.set(index, value);
        onChanged();
      } else {
        recipientsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .pbmse.EncryptionRecipient recipients = 5;</code>
     */
    public Builder setRecipients(
        int index, trinsic.okapi.pbmse.EncryptionRecipient.Builder builderForValue) {
      if (recipientsBuilder_ == null) {
        ensureRecipientsIsMutable();
        recipients_.set(index, builderForValue.build());
        onChanged();
      } else {
        recipientsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .pbmse.EncryptionRecipient recipients = 5;</code>
     */
    public Builder addRecipients(trinsic.okapi.pbmse.EncryptionRecipient value) {
      if (recipientsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRecipientsIsMutable();
        recipients_.add(value);
        onChanged();
      } else {
        recipientsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .pbmse.EncryptionRecipient recipients = 5;</code>
     */
    public Builder addRecipients(
        int index, trinsic.okapi.pbmse.EncryptionRecipient value) {
      if (recipientsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRecipientsIsMutable();
        recipients_.add(index, value);
        onChanged();
      } else {
        recipientsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .pbmse.EncryptionRecipient recipients = 5;</code>
     */
    public Builder addRecipients(
        trinsic.okapi.pbmse.EncryptionRecipient.Builder builderForValue) {
      if (recipientsBuilder_ == null) {
        ensureRecipientsIsMutable();
        recipients_.add(builderForValue.build());
        onChanged();
      } else {
        recipientsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .pbmse.EncryptionRecipient recipients = 5;</code>
     */
    public Builder addRecipients(
        int index, trinsic.okapi.pbmse.EncryptionRecipient.Builder builderForValue) {
      if (recipientsBuilder_ == null) {
        ensureRecipientsIsMutable();
        recipients_.add(index, builderForValue.build());
        onChanged();
      } else {
        recipientsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .pbmse.EncryptionRecipient recipients = 5;</code>
     */
    public Builder addAllRecipients(
        java.lang.Iterable<? extends trinsic.okapi.pbmse.EncryptionRecipient> values) {
      if (recipientsBuilder_ == null) {
        ensureRecipientsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, recipients_);
        onChanged();
      } else {
        recipientsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .pbmse.EncryptionRecipient recipients = 5;</code>
     */
    public Builder clearRecipients() {
      if (recipientsBuilder_ == null) {
        recipients_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        recipientsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .pbmse.EncryptionRecipient recipients = 5;</code>
     */
    public Builder removeRecipients(int index) {
      if (recipientsBuilder_ == null) {
        ensureRecipientsIsMutable();
        recipients_.remove(index);
        onChanged();
      } else {
        recipientsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .pbmse.EncryptionRecipient recipients = 5;</code>
     */
    public trinsic.okapi.pbmse.EncryptionRecipient.Builder getRecipientsBuilder(
        int index) {
      return getRecipientsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .pbmse.EncryptionRecipient recipients = 5;</code>
     */
    public trinsic.okapi.pbmse.EncryptionRecipientOrBuilder getRecipientsOrBuilder(
        int index) {
      if (recipientsBuilder_ == null) {
        return recipients_.get(index);  } else {
        return recipientsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .pbmse.EncryptionRecipient recipients = 5;</code>
     */
    public java.util.List<? extends trinsic.okapi.pbmse.EncryptionRecipientOrBuilder> 
         getRecipientsOrBuilderList() {
      if (recipientsBuilder_ != null) {
        return recipientsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(recipients_);
      }
    }
    /**
     * <code>repeated .pbmse.EncryptionRecipient recipients = 5;</code>
     */
    public trinsic.okapi.pbmse.EncryptionRecipient.Builder addRecipientsBuilder() {
      return getRecipientsFieldBuilder().addBuilder(
          trinsic.okapi.pbmse.EncryptionRecipient.getDefaultInstance());
    }
    /**
     * <code>repeated .pbmse.EncryptionRecipient recipients = 5;</code>
     */
    public trinsic.okapi.pbmse.EncryptionRecipient.Builder addRecipientsBuilder(
        int index) {
      return getRecipientsFieldBuilder().addBuilder(
          index, trinsic.okapi.pbmse.EncryptionRecipient.getDefaultInstance());
    }
    /**
     * <code>repeated .pbmse.EncryptionRecipient recipients = 5;</code>
     */
    public java.util.List<trinsic.okapi.pbmse.EncryptionRecipient.Builder> 
         getRecipientsBuilderList() {
      return getRecipientsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        trinsic.okapi.pbmse.EncryptionRecipient, trinsic.okapi.pbmse.EncryptionRecipient.Builder, trinsic.okapi.pbmse.EncryptionRecipientOrBuilder> 
        getRecipientsFieldBuilder() {
      if (recipientsBuilder_ == null) {
        recipientsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            trinsic.okapi.pbmse.EncryptionRecipient, trinsic.okapi.pbmse.EncryptionRecipient.Builder, trinsic.okapi.pbmse.EncryptionRecipientOrBuilder>(
                recipients_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        recipients_ = null;
      }
      return recipientsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:pbmse.EncryptedMessage)
  }

  // @@protoc_insertion_point(class_scope:pbmse.EncryptedMessage)
  private static final trinsic.okapi.pbmse.EncryptedMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new trinsic.okapi.pbmse.EncryptedMessage();
  }

  public static trinsic.okapi.pbmse.EncryptedMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EncryptedMessage>
      PARSER = new com.google.protobuf.AbstractParser<EncryptedMessage>() {
    @java.lang.Override
    public EncryptedMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new EncryptedMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<EncryptedMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EncryptedMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public trinsic.okapi.pbmse.EncryptedMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

