// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pbmse/pbmse.proto

package trinsic.okapi.pbmse;

/**
 * Protobuf enum {@code pbmse.EncryptionAlgorithm}
 */
public enum EncryptionAlgorithm
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>xchacha20poly1305 = 0;</code>
   */
  xchacha20poly1305(0),
  /**
   * <code>aes_gcm = 1;</code>
   */
  aes_gcm(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>xchacha20poly1305 = 0;</code>
   */
  public static final int xchacha20poly1305_VALUE = 0;
  /**
   * <code>aes_gcm = 1;</code>
   */
  public static final int aes_gcm_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static EncryptionAlgorithm valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static EncryptionAlgorithm forNumber(int value) {
    switch (value) {
      case 0: return xchacha20poly1305;
      case 1: return aes_gcm;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<EncryptionAlgorithm>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      EncryptionAlgorithm> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<EncryptionAlgorithm>() {
          public EncryptionAlgorithm findValueByNumber(int number) {
            return EncryptionAlgorithm.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return trinsic.okapi.pbmse.Pbmse.getDescriptor().getEnumTypes().get(1);
  }

  private static final EncryptionAlgorithm[] VALUES = values();

  public static EncryptionAlgorithm valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private EncryptionAlgorithm(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:pbmse.EncryptionAlgorithm)
}

