# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: examples.proto

require 'google/protobuf'

require_relative 'pbmse/pbmse_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("examples.proto", :syntax => :proto3) do
    add_message "okapi.examples.BasicMessage" do
      optional :text, :string, 1
    end
  end
end

module Okapi
  module Examples
    BasicMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("okapi.examples.BasicMessage").msgclass
  end
end
