// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transport.proto

package trinsic.okapi.transport;

public interface PackResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:okapi.transport.PackResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.pbmse.EncryptedMessage message = 1;</code>
   * @return Whether the message field is set.
   */
  boolean hasMessage();
  /**
   * <code>.pbmse.EncryptedMessage message = 1;</code>
   * @return The message.
   */
  trinsic.okapi.pbmse.EncryptedMessage getMessage();
  /**
   * <code>.pbmse.EncryptedMessage message = 1;</code>
   */
  trinsic.okapi.pbmse.EncryptedMessageOrBuilder getMessageOrBuilder();
}
