//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: pbmse/v1/pbmse.proto

package trinsic.okapi.pbmse.v1;

@kotlin.jvm.JvmSynthetic
inline fun encryptionHeader(block: trinsic.okapi.pbmse.v1.EncryptionHeaderKt.Dsl.() -> Unit): trinsic.okapi.pbmse.v1.Pbmse.EncryptionHeader =
  trinsic.okapi.pbmse.v1.EncryptionHeaderKt.Dsl._create(trinsic.okapi.pbmse.v1.Pbmse.EncryptionHeader.newBuilder()).apply { block() }._build()
object EncryptionHeaderKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: trinsic.okapi.pbmse.v1.Pbmse.EncryptionHeader.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: trinsic.okapi.pbmse.v1.Pbmse.EncryptionHeader.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): trinsic.okapi.pbmse.v1.Pbmse.EncryptionHeader = _builder.build()

    /**
     * <code>.pbmse.v1.EncryptionMode mode = 1 [json_name = "enc"];</code>
     */
    var mode: trinsic.okapi.pbmse.v1.Pbmse.EncryptionMode
      @JvmName("getMode")
      get() = _builder.getMode()
      @JvmName("setMode")
      set(value) {
        _builder.setMode(value)
      }
    /**
     * <code>.pbmse.v1.EncryptionMode mode = 1 [json_name = "enc"];</code>
     */
    fun clearMode() {
      _builder.clearMode()
    }

    /**
     * <code>.pbmse.v1.EncryptionAlgorithm algorithm = 2 [json_name = "alg"];</code>
     */
    var algorithm: trinsic.okapi.pbmse.v1.Pbmse.EncryptionAlgorithm
      @JvmName("getAlgorithm")
      get() = _builder.getAlgorithm()
      @JvmName("setAlgorithm")
      set(value) {
        _builder.setAlgorithm(value)
      }
    /**
     * <code>.pbmse.v1.EncryptionAlgorithm algorithm = 2 [json_name = "alg"];</code>
     */
    fun clearAlgorithm() {
      _builder.clearAlgorithm()
    }

    /**
     * <code>string key_id = 3 [json_name = "kid"];</code>
     */
    var keyId: kotlin.String
      @JvmName("getKeyId")
      get() = _builder.getKeyId()
      @JvmName("setKeyId")
      set(value) {
        _builder.setKeyId(value)
      }
    /**
     * <code>string key_id = 3 [json_name = "kid"];</code>
     */
    fun clearKeyId() {
      _builder.clearKeyId()
    }

    /**
     * <code>string sender_key_id = 4 [json_name = "skid"];</code>
     */
    var senderKeyId: kotlin.String
      @JvmName("getSenderKeyId")
      get() = _builder.getSenderKeyId()
      @JvmName("setSenderKeyId")
      set(value) {
        _builder.setSenderKeyId(value)
      }
    /**
     * <code>string sender_key_id = 4 [json_name = "skid"];</code>
     */
    fun clearSenderKeyId() {
      _builder.clearSenderKeyId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun trinsic.okapi.pbmse.v1.Pbmse.EncryptionHeader.copy(block: trinsic.okapi.pbmse.v1.EncryptionHeaderKt.Dsl.() -> Unit): trinsic.okapi.pbmse.v1.Pbmse.EncryptionHeader =
  trinsic.okapi.pbmse.v1.EncryptionHeaderKt.Dsl._create(this.toBuilder()).apply { block() }._build()
