//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: okapi/transport/v1/transport.proto

package trinsic.okapi.transport.v1;

@kotlin.jvm.JvmSynthetic
inline fun coreMessage(block: trinsic.okapi.transport.v1.CoreMessageKt.Dsl.() -> Unit): trinsic.okapi.transport.v1.Transport.CoreMessage =
  trinsic.okapi.transport.v1.CoreMessageKt.Dsl._create(trinsic.okapi.transport.v1.Transport.CoreMessage.newBuilder()).apply { block() }._build()
object CoreMessageKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: trinsic.okapi.transport.v1.Transport.CoreMessage.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: trinsic.okapi.transport.v1.Transport.CoreMessage.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): trinsic.okapi.transport.v1.Transport.CoreMessage = _builder.build()

    /**
     * <code>string id = 1;</code>
     */
    var id: kotlin.String
      @JvmName("getId")
      get() = _builder.getId()
      @JvmName("setId")
      set(value) {
        _builder.setId(value)
      }
    /**
     * <code>string id = 1;</code>
     */
    fun clearId() {
      _builder.clearId()
    }

    /**
     * <code>string type = 2;</code>
     */
    var type: kotlin.String
      @JvmName("getType")
      get() = _builder.getType()
      @JvmName("setType")
      set(value) {
        _builder.setType(value)
      }
    /**
     * <code>string type = 2;</code>
     */
    fun clearType() {
      _builder.clearType()
    }

    /**
     * <code>bytes body = 3;</code>
     */
    var body: com.google.protobuf.ByteString
      @JvmName("getBody")
      get() = _builder.getBody()
      @JvmName("setBody")
      set(value) {
        _builder.setBody(value)
      }
    /**
     * <code>bytes body = 3;</code>
     */
    fun clearBody() {
      _builder.clearBody()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    class ToProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated string to = 4;</code>
     * @return A list containing the to.
     */
    val to: com.google.protobuf.kotlin.DslList<kotlin.String, ToProxy>
      @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getToList()
      )
    /**
     * <code>repeated string to = 4;</code>
     * @param value The to to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addTo")
    fun com.google.protobuf.kotlin.DslList<kotlin.String, ToProxy>.add(value: kotlin.String) {
      _builder.addTo(value)
    }
    /**
     * <code>repeated string to = 4;</code>
     * @param value The to to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignTo")
    operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ToProxy>.plusAssign(value: kotlin.String) {
      _builder.addTo(value)
    }
    /**
     * <code>repeated string to = 4;</code>
     * @param values The to to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllTo")
    fun com.google.protobuf.kotlin.DslList<kotlin.String, ToProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllTo(values)
    }
    /**
     * <code>repeated string to = 4;</code>
     * @param values The to to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllTo")
    operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ToProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllTo(values)
    }
    /**
     * <code>repeated string to = 4;</code>
     * @param index The index to set the value at.
     * @param value The to to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setTo")
    operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ToProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setTo(index, value)
    }/**
     * <code>repeated string to = 4;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearTo")
    fun com.google.protobuf.kotlin.DslList<kotlin.String, ToProxy>.clear() {
      _builder.clearTo()
    }
    /**
     * <code>string from = 5;</code>
     */
    var from: kotlin.String
      @JvmName("getFrom")
      get() = _builder.getFrom()
      @JvmName("setFrom")
      set(value) {
        _builder.setFrom(value)
      }
    /**
     * <code>string from = 5;</code>
     */
    fun clearFrom() {
      _builder.clearFrom()
    }

    /**
     * <code>int64 created = 6 [json_name = "created_time"];</code>
     */
    var created: kotlin.Long
      @JvmName("getCreated")
      get() = _builder.getCreated()
      @JvmName("setCreated")
      set(value) {
        _builder.setCreated(value)
      }
    /**
     * <code>int64 created = 6 [json_name = "created_time"];</code>
     */
    fun clearCreated() {
      _builder.clearCreated()
    }

    /**
     * <code>int64 expires = 7 [json_name = "expires_time"];</code>
     */
    var expires: kotlin.Long
      @JvmName("getExpires")
      get() = _builder.getExpires()
      @JvmName("setExpires")
      set(value) {
        _builder.setExpires(value)
      }
    /**
     * <code>int64 expires = 7 [json_name = "expires_time"];</code>
     */
    fun clearExpires() {
      _builder.clearExpires()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun trinsic.okapi.transport.v1.Transport.CoreMessage.copy(block: trinsic.okapi.transport.v1.CoreMessageKt.Dsl.() -> Unit): trinsic.okapi.transport.v1.Transport.CoreMessage =
  trinsic.okapi.transport.v1.CoreMessageKt.Dsl._create(this.toBuilder()).apply { block() }._build()
