//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: okapi/transport/v1/transport.proto

package trinsic.okapi.transport.v1;

@kotlin.jvm.JvmSynthetic
inline fun signRequest(block: trinsic.okapi.transport.v1.SignRequestKt.Dsl.() -> Unit): trinsic.okapi.transport.v1.Transport.SignRequest =
  trinsic.okapi.transport.v1.SignRequestKt.Dsl._create(trinsic.okapi.transport.v1.Transport.SignRequest.newBuilder()).apply { block() }._build()
object SignRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: trinsic.okapi.transport.v1.Transport.SignRequest.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: trinsic.okapi.transport.v1.Transport.SignRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): trinsic.okapi.transport.v1.Transport.SignRequest = _builder.build()

    /**
     * <code>bytes payload = 1;</code>
     */
    var payload: com.google.protobuf.ByteString
      @JvmName("getPayload")
      get() = _builder.getPayload()
      @JvmName("setPayload")
      set(value) {
        _builder.setPayload(value)
      }
    /**
     * <code>bytes payload = 1;</code>
     */
    fun clearPayload() {
      _builder.clearPayload()
    }

    /**
     * <code>.okapi.keys.v1.JsonWebKey key = 2;</code>
     */
    var key: trinsic.okapi.keys.v1.Keys.JsonWebKey
      @JvmName("getKey")
      get() = _builder.getKey()
      @JvmName("setKey")
      set(value) {
        _builder.setKey(value)
      }
    /**
     * <code>.okapi.keys.v1.JsonWebKey key = 2;</code>
     */
    fun clearKey() {
      _builder.clearKey()
    }
    /**
     * <code>.okapi.keys.v1.JsonWebKey key = 2;</code>
     * @return Whether the key field is set.
     */
    fun hasKey(): kotlin.Boolean {
      return _builder.hasKey()
    }

    /**
     * <code>.pbmse.v1.SignedMessage append_to = 3;</code>
     */
    var appendTo: trinsic.okapi.pbmse.v1.Pbmse.SignedMessage
      @JvmName("getAppendTo")
      get() = _builder.getAppendTo()
      @JvmName("setAppendTo")
      set(value) {
        _builder.setAppendTo(value)
      }
    /**
     * <code>.pbmse.v1.SignedMessage append_to = 3;</code>
     */
    fun clearAppendTo() {
      _builder.clearAppendTo()
    }
    /**
     * <code>.pbmse.v1.SignedMessage append_to = 3;</code>
     * @return Whether the appendTo field is set.
     */
    fun hasAppendTo(): kotlin.Boolean {
      return _builder.hasAppendTo()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun trinsic.okapi.transport.v1.Transport.SignRequest.copy(block: trinsic.okapi.transport.v1.SignRequestKt.Dsl.() -> Unit): trinsic.okapi.transport.v1.Transport.SignRequest =
  trinsic.okapi.transport.v1.SignRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()
