# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: security.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='security.proto',
  package='didcomm.messaging',
  syntax='proto3',
  serialized_options=b'\252\002\021DIDComm.Messaging',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0esecurity.proto\x12\x11\x64idcomm.messaging\"R\n\rSignedMessage\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\x12\x30\n\nsignatures\x18\x02 \x03(\x0b\x32\x1c.didcomm.messaging.Signature\".\n\tSignature\x12\x0e\n\x06header\x18\x01 \x01(\x0c\x12\x11\n\tsignature\x18\x03 \x01(\x0c\"4\n\x0fSignatureHeader\x12\x11\n\talgorithm\x18\x01 \x01(\t\x12\x0e\n\x06key_id\x18\x02 \x01(\t\"\x9d\x01\n\x10\x45ncryptedMessage\x12\x0e\n\x02iv\x18\x01 \x01(\x0cR\x02iv\x12\x10\n\x03\x61\x61\x64\x18\x02 \x01(\x0cR\x03\x61\x61\x64\x12\x1e\n\nciphertext\x18\x03 \x01(\x0cR\nciphertext\x12\x0b\n\x03tag\x18\x04 \x01(\x0c\x12:\n\nrecipients\x18\x05 \x03(\x0b\x32&.didcomm.messaging.EncryptionRecipient\"\xba\x01\n\x10\x45ncryptionHeader\x12\x34\n\x04mode\x18\x01 \x01(\x0e\x32!.didcomm.messaging.EncryptionModeR\x03\x65nc\x12>\n\talgorithm\x18\x02 \x01(\x0e\x32&.didcomm.messaging.EncryptionAlgorithmR\x03\x61lg\x12\x13\n\x06key_id\x18\x03 \x01(\tR\x03kid\x12\x1b\n\rsender_key_id\x18\x04 \x01(\tR\x04skid\"|\n\x13\x45ncryptionRecipient\x12@\n\x06header\x18\x01 \x01(\x0b\x32#.didcomm.messaging.EncryptionHeaderR\x0bunprotected\x12#\n\x16\x63ontent_encryption_key\x18\x02 \x01(\x0cR\x03\x63\x65k*8\n\x0e\x45ncryptionMode\x12\n\n\x06\x64irect\x10\x00\x12\x1a\n\x16\x63ontent_encryption_key\x10\x01*9\n\x13\x45ncryptionAlgorithm\x12\x15\n\x11xchacha20poly1305\x10\x00\x12\x0b\n\x07\x61\x65s_gcm\x10\x01\x42\x14\xaa\x02\x11\x44IDComm.Messagingb\x06proto3'
)

_ENCRYPTIONMODE = _descriptor.EnumDescriptor(
  name='EncryptionMode',
  full_name='didcomm.messaging.EncryptionMode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='direct', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='content_encryption_key', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=698,
  serialized_end=754,
)
_sym_db.RegisterEnumDescriptor(_ENCRYPTIONMODE)

EncryptionMode = enum_type_wrapper.EnumTypeWrapper(_ENCRYPTIONMODE)
_ENCRYPTIONALGORITHM = _descriptor.EnumDescriptor(
  name='EncryptionAlgorithm',
  full_name='didcomm.messaging.EncryptionAlgorithm',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='xchacha20poly1305', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='aes_gcm', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=756,
  serialized_end=813,
)
_sym_db.RegisterEnumDescriptor(_ENCRYPTIONALGORITHM)

EncryptionAlgorithm = enum_type_wrapper.EnumTypeWrapper(_ENCRYPTIONALGORITHM)
direct = 0
content_encryption_key = 1
xchacha20poly1305 = 0
aes_gcm = 1



_SIGNEDMESSAGE = _descriptor.Descriptor(
  name='SignedMessage',
  full_name='didcomm.messaging.SignedMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='payload', full_name='didcomm.messaging.SignedMessage.payload', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='signatures', full_name='didcomm.messaging.SignedMessage.signatures', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=119,
)


_SIGNATURE = _descriptor.Descriptor(
  name='Signature',
  full_name='didcomm.messaging.Signature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='didcomm.messaging.Signature.header', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='signature', full_name='didcomm.messaging.Signature.signature', index=1,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=167,
)


_SIGNATUREHEADER = _descriptor.Descriptor(
  name='SignatureHeader',
  full_name='didcomm.messaging.SignatureHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='algorithm', full_name='didcomm.messaging.SignatureHeader.algorithm', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key_id', full_name='didcomm.messaging.SignatureHeader.key_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=169,
  serialized_end=221,
)


_ENCRYPTEDMESSAGE = _descriptor.Descriptor(
  name='EncryptedMessage',
  full_name='didcomm.messaging.EncryptedMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='iv', full_name='didcomm.messaging.EncryptedMessage.iv', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='iv', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='aad', full_name='didcomm.messaging.EncryptedMessage.aad', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='aad', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ciphertext', full_name='didcomm.messaging.EncryptedMessage.ciphertext', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='ciphertext', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tag', full_name='didcomm.messaging.EncryptedMessage.tag', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='recipients', full_name='didcomm.messaging.EncryptedMessage.recipients', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=224,
  serialized_end=381,
)


_ENCRYPTIONHEADER = _descriptor.Descriptor(
  name='EncryptionHeader',
  full_name='didcomm.messaging.EncryptionHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mode', full_name='didcomm.messaging.EncryptionHeader.mode', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='enc', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='algorithm', full_name='didcomm.messaging.EncryptionHeader.algorithm', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='alg', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key_id', full_name='didcomm.messaging.EncryptionHeader.key_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='kid', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sender_key_id', full_name='didcomm.messaging.EncryptionHeader.sender_key_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='skid', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=384,
  serialized_end=570,
)


_ENCRYPTIONRECIPIENT = _descriptor.Descriptor(
  name='EncryptionRecipient',
  full_name='didcomm.messaging.EncryptionRecipient',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='didcomm.messaging.EncryptionRecipient.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='unprotected', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='content_encryption_key', full_name='didcomm.messaging.EncryptionRecipient.content_encryption_key', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='cek', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=572,
  serialized_end=696,
)

_SIGNEDMESSAGE.fields_by_name['signatures'].message_type = _SIGNATURE
_ENCRYPTEDMESSAGE.fields_by_name['recipients'].message_type = _ENCRYPTIONRECIPIENT
_ENCRYPTIONHEADER.fields_by_name['mode'].enum_type = _ENCRYPTIONMODE
_ENCRYPTIONHEADER.fields_by_name['algorithm'].enum_type = _ENCRYPTIONALGORITHM
_ENCRYPTIONRECIPIENT.fields_by_name['header'].message_type = _ENCRYPTIONHEADER
DESCRIPTOR.message_types_by_name['SignedMessage'] = _SIGNEDMESSAGE
DESCRIPTOR.message_types_by_name['Signature'] = _SIGNATURE
DESCRIPTOR.message_types_by_name['SignatureHeader'] = _SIGNATUREHEADER
DESCRIPTOR.message_types_by_name['EncryptedMessage'] = _ENCRYPTEDMESSAGE
DESCRIPTOR.message_types_by_name['EncryptionHeader'] = _ENCRYPTIONHEADER
DESCRIPTOR.message_types_by_name['EncryptionRecipient'] = _ENCRYPTIONRECIPIENT
DESCRIPTOR.enum_types_by_name['EncryptionMode'] = _ENCRYPTIONMODE
DESCRIPTOR.enum_types_by_name['EncryptionAlgorithm'] = _ENCRYPTIONALGORITHM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SignedMessage = _reflection.GeneratedProtocolMessageType('SignedMessage', (_message.Message,), {
  'DESCRIPTOR' : _SIGNEDMESSAGE,
  '__module__' : 'security_pb2'
  # @@protoc_insertion_point(class_scope:didcomm.messaging.SignedMessage)
  })
_sym_db.RegisterMessage(SignedMessage)

Signature = _reflection.GeneratedProtocolMessageType('Signature', (_message.Message,), {
  'DESCRIPTOR' : _SIGNATURE,
  '__module__' : 'security_pb2'
  # @@protoc_insertion_point(class_scope:didcomm.messaging.Signature)
  })
_sym_db.RegisterMessage(Signature)

SignatureHeader = _reflection.GeneratedProtocolMessageType('SignatureHeader', (_message.Message,), {
  'DESCRIPTOR' : _SIGNATUREHEADER,
  '__module__' : 'security_pb2'
  # @@protoc_insertion_point(class_scope:didcomm.messaging.SignatureHeader)
  })
_sym_db.RegisterMessage(SignatureHeader)

EncryptedMessage = _reflection.GeneratedProtocolMessageType('EncryptedMessage', (_message.Message,), {
  'DESCRIPTOR' : _ENCRYPTEDMESSAGE,
  '__module__' : 'security_pb2'
  # @@protoc_insertion_point(class_scope:didcomm.messaging.EncryptedMessage)
  })
_sym_db.RegisterMessage(EncryptedMessage)

EncryptionHeader = _reflection.GeneratedProtocolMessageType('EncryptionHeader', (_message.Message,), {
  'DESCRIPTOR' : _ENCRYPTIONHEADER,
  '__module__' : 'security_pb2'
  # @@protoc_insertion_point(class_scope:didcomm.messaging.EncryptionHeader)
  })
_sym_db.RegisterMessage(EncryptionHeader)

EncryptionRecipient = _reflection.GeneratedProtocolMessageType('EncryptionRecipient', (_message.Message,), {
  'DESCRIPTOR' : _ENCRYPTIONRECIPIENT,
  '__module__' : 'security_pb2'
  # @@protoc_insertion_point(class_scope:didcomm.messaging.EncryptionRecipient)
  })
_sym_db.RegisterMessage(EncryptionRecipient)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
