# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: okapi/metadata/metadata.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file('okapi/metadata/metadata.proto', syntax: :proto3) do
    add_message 'okapi.metadata.MetadataRequest' do
    end
    add_message 'okapi.metadata.MetadataResponse' do
      optional :version, :string, 1
      optional :version_major, :int32, 2
      optional :version_minor, :int32, 3
      optional :version_patch, :int32, 4
      optional :target_family, :string, 10
      optional :target_os, :string, 11
      optional :target_arch, :string, 12
      optional :target_vendor, :string, 13
      optional :target_env, :string, 14
    end
  end
end

module Okapi
  module Metadata
    MetadataRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup('okapi.metadata.MetadataRequest').msgclass
    MetadataResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup('okapi.metadata.MetadataResponse').msgclass
  end
end
