// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: examples.proto

package trinsic.okapi.examples;

public interface BasicMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:okapi.examples.BasicMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string text = 1;</code>
   * @return The text.
   */
  java.lang.String getText();
  /**
   * <code>string text = 1;</code>
   * @return The bytes for text.
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
