// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.1
// source: okapi/metadata/metadata.proto

package metadata

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request custom metadata about the native okapi binaries - cannot get cargo env vars at runtime
type MetadataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MetadataRequest) Reset() {
	*x = MetadataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_okapi_metadata_metadata_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataRequest) ProtoMessage() {}

func (x *MetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_okapi_metadata_metadata_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataRequest.ProtoReflect.Descriptor instead.
func (*MetadataRequest) Descriptor() ([]byte, []int) {
	return file_okapi_metadata_metadata_proto_rawDescGZIP(), []int{0}
}

// Metadata information about the native okapi binaries. Always returns the version information
type MetadataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version      string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`                                // The full version string from okapi
	VersionMajor int32  `protobuf:"varint,2,opt,name=version_major,json=versionMajor,proto3" json:"version_major,omitempty"` // Major version
	VersionMinor int32  `protobuf:"varint,3,opt,name=version_minor,json=versionMinor,proto3" json:"version_minor,omitempty"` // Minor version
	VersionPatch int32  `protobuf:"varint,4,opt,name=version_patch,json=versionPatch,proto3" json:"version_patch,omitempty"` // Patch release version
	// https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-crates
	TargetFamily string `protobuf:"bytes,10,opt,name=target_family,json=targetFamily,proto3" json:"target_family,omitempty"`
	TargetOs     string `protobuf:"bytes,11,opt,name=target_os,json=targetOs,proto3" json:"target_os,omitempty"`
	TargetArch   string `protobuf:"bytes,12,opt,name=target_arch,json=targetArch,proto3" json:"target_arch,omitempty"`
	TargetVendor string `protobuf:"bytes,13,opt,name=target_vendor,json=targetVendor,proto3" json:"target_vendor,omitempty"`
	TargetEnv    string `protobuf:"bytes,14,opt,name=target_env,json=targetEnv,proto3" json:"target_env,omitempty"`
}

func (x *MetadataResponse) Reset() {
	*x = MetadataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_okapi_metadata_metadata_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataResponse) ProtoMessage() {}

func (x *MetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_okapi_metadata_metadata_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataResponse.ProtoReflect.Descriptor instead.
func (*MetadataResponse) Descriptor() ([]byte, []int) {
	return file_okapi_metadata_metadata_proto_rawDescGZIP(), []int{1}
}

func (x *MetadataResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *MetadataResponse) GetVersionMajor() int32 {
	if x != nil {
		return x.VersionMajor
	}
	return 0
}

func (x *MetadataResponse) GetVersionMinor() int32 {
	if x != nil {
		return x.VersionMinor
	}
	return 0
}

func (x *MetadataResponse) GetVersionPatch() int32 {
	if x != nil {
		return x.VersionPatch
	}
	return 0
}

func (x *MetadataResponse) GetTargetFamily() string {
	if x != nil {
		return x.TargetFamily
	}
	return ""
}

func (x *MetadataResponse) GetTargetOs() string {
	if x != nil {
		return x.TargetOs
	}
	return ""
}

func (x *MetadataResponse) GetTargetArch() string {
	if x != nil {
		return x.TargetArch
	}
	return ""
}

func (x *MetadataResponse) GetTargetVendor() string {
	if x != nil {
		return x.TargetVendor
	}
	return ""
}

func (x *MetadataResponse) GetTargetEnv() string {
	if x != nil {
		return x.TargetEnv
	}
	return ""
}

var File_okapi_metadata_metadata_proto protoreflect.FileDescriptor

var file_okapi_metadata_metadata_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x6f, 0x6b, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x2f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0e, 0x6f, 0x6b, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x22,
	0x11, 0x0a, 0x0f, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0xc2, 0x02, 0x0a, 0x10, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x61, 0x6a,
	0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x4d, 0x61, 0x6a, 0x6f, 0x72, 0x12, 0x23, 0x0a, 0x0d, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x5f, 0x6d, 0x69, 0x6e, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x4d, 0x69, 0x6e, 0x6f, 0x72, 0x12, 0x23, 0x0a, 0x0d, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x70, 0x61, 0x74, 0x63, 0x68, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0c, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x74, 0x63, 0x68,
	0x12, 0x23, 0x0a, 0x0d, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x66, 0x61, 0x6d, 0x69, 0x6c,
	0x79, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x46,
	0x61, 0x6d, 0x69, 0x6c, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f,
	0x6f, 0x73, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x4f, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x61, 0x72, 0x63,
	0x68, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x41,
	0x72, 0x63, 0x68, 0x12, 0x23, 0x0a, 0x0d, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x76, 0x65,
	0x6e, 0x64, 0x6f, 0x72, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x74, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x56, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x5f, 0x65, 0x6e, 0x76, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x45, 0x6e, 0x76, 0x42, 0x39, 0x0a, 0x16, 0x74, 0x72, 0x69, 0x6e, 0x73,
	0x69, 0x63, 0x2e, 0x6f, 0x6b, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x5a, 0x0e, 0x6f, 0x6b, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0xaa, 0x02, 0x0e, 0x4f, 0x6b, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_okapi_metadata_metadata_proto_rawDescOnce sync.Once
	file_okapi_metadata_metadata_proto_rawDescData = file_okapi_metadata_metadata_proto_rawDesc
)

func file_okapi_metadata_metadata_proto_rawDescGZIP() []byte {
	file_okapi_metadata_metadata_proto_rawDescOnce.Do(func() {
		file_okapi_metadata_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(file_okapi_metadata_metadata_proto_rawDescData)
	})
	return file_okapi_metadata_metadata_proto_rawDescData
}

var file_okapi_metadata_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_okapi_metadata_metadata_proto_goTypes = []interface{}{
	(*MetadataRequest)(nil),  // 0: okapi.metadata.MetadataRequest
	(*MetadataResponse)(nil), // 1: okapi.metadata.MetadataResponse
}
var file_okapi_metadata_metadata_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_okapi_metadata_metadata_proto_init() }
func file_okapi_metadata_metadata_proto_init() {
	if File_okapi_metadata_metadata_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_okapi_metadata_metadata_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetadataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_okapi_metadata_metadata_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetadataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_okapi_metadata_metadata_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_okapi_metadata_metadata_proto_goTypes,
		DependencyIndexes: file_okapi_metadata_metadata_proto_depIdxs,
		MessageInfos:      file_okapi_metadata_metadata_proto_msgTypes,
	}.Build()
	File_okapi_metadata_metadata_proto = out.File
	file_okapi_metadata_metadata_proto_rawDesc = nil
	file_okapi_metadata_metadata_proto_goTypes = nil
	file_okapi_metadata_metadata_proto_depIdxs = nil
}
