name: Build Proto Files
on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "proto/**"
      - "devops/*.py"
  pull_request:
    paths:
      - "proto/**"
      - "devops/**"
      - ".github/workflows/build-proto.yml"

jobs:
  compile_proto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.17
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
      - name: Configure git credentials
        uses: OleksiyRudenko/gha-git-credentials@v2
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
      - name: Install protobuf plugins
        run: |
          pip install -r ./devops/requirements.txt
          python ./devops/generate_proto_files.py --download-plugins --language=none
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: Compile proto files
        run: |
          python ./devops/generate_proto_files.py --language=all

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        id: commit_changes
        with:
            author_name: Mewmba
            author_email: mewmba@trinsic.id
            message: 'Generated okapi sdk code from proto files on branch'
            new_branch: 'mewmba-generated-proto-code'
            push: --set-upstream origin mewmba-generated-proto-code --force

      - name: pull-request
        uses: repo-sync/pull-request@v2
        if: ${{ steps.commit_changes.outputs.committed == 'true' }}
        with:
            source_branch: 'mewmba-generated-proto-code'  # From previous step
            destination_branch: ${{ github.head_ref }}
            pr_title: 'Generated Protos for Okapi'
            pr_body: ":rocket: Generated protos"
            pr_allow_empty: false
            github_token: ${{ secrets.GITHUB_TOKEN }}
