name: Build Swift SDK

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "swift/**"
      - "proto/**"
      - ".github/workflows/*swift*"
  push:
    branches:
      - main

jobs:
  test_swift:
    name: Test Swift code
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download workflow artifact
        uses: dawidd6/action-download-artifact@v2.14.0
        with:
          workflow: "build-libs.yml"
          path: ./libs
      - name: Build, Test, Pack
        run: ./devops/BuildSwift.ps1 -GitTag ${{ github.ref }}
        shell: pwsh
