name: Build Swift SDK

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "swift/**"
      - "proto/**"
      - ".github/workflows/*swift*"
  push:
    branches:
      - main

jobs:
  test_swift:
    name: Test Swift code
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download workflow artifact
        uses: dawidd6/action-download-artifact@v2.14.0
        with:
          workflow: "build-libs.yml"
          path: ./libs
      - name: Copy static libraries
        run: |
          $source = "./libs"
          $dest = "./swift/Okapi/OkapiObjectiveC"
          Get-ChildItem $source -Recurse | `
              Where-Object { $_.PSIsContainer -eq $False } | `
              ForEach-Object {Copy-Item -Path $_.Fullname -Destination $dest -Force} # Do the things
      - name: Build, Test, Pack
        run:  |
          swift build
          swift test
        shell: pwsh
        with:
          path: ./swift/Okapi
      # - name: Publish Unit Test Results
      #   uses: EnricoMi/publish-unit-test-result-action/composite@v1.18
      #   with:
      #     files: swift/test_output.xml
      #     comment_mode: "create new"
      #     hide_comments: "off"
      #     check_name: "Swift Unit Test Results"
