name: Wasm

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    paths:
      - "wasm/**"
      - "proto/**"
      - ".github/workflows/*wasm*"
      - "devops/**"
  push:
    branches:
      - main
    paths:
      - "wasm/**"
      - "proto/**"
      - ".github/workflows/*wasm*"
      - "devops/**"

jobs:
  build_test:
    name: Build, Test
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./wasm
    steps:
      - uses: actions/checkout@v3
      - uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: 'latest'
      - run: |
          rustup toolchain uninstall stable
          rustup toolchain install stable
          rustup toolchain install stable --target wasm32-unknown-unknown
      - run: |
          npm install
          npm run build:proto
          npm run build:wasm:node
          npm run test:node
          npm run build:wasm:browser
          npm run test:browser
        shell: pwsh
        working-directory: ./wasm/packages/okapi
