name: Wasm

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    paths:
      - "wasm/**"
      - "proto/**"
      - ".github/workflows/*wasm*"
      - "devops/**"
  push:
    branches:
      - main
    paths:
      - "wasm/**"
      - "proto/**"
      - ".github/workflows/*wasm*"
      - "devops/**"

jobs:
  build_test:
    name: Build, Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]  # windows-latest has issues with wasm-pack.exe
        node-version: [ 14, 16, 18 ]
        target: [ 'node', 'browser' ]
    defaults:
      run:
        working-directory: ./wasm
    steps:
      - uses: actions/checkout@v3
      - name: Setup protoc
        uses: arduino/setup-protoc@v1.1.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: 'latest'
      - uses: actions/setup-node@v3
        name: Setup Node v${{ matrix.node-version }}
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          rustup toolchain uninstall stable
          rustup toolchain install stable
          rustup toolchain install stable --target wasm32-unknown-unknown
      - run: |
          npm install
          npm run build
          npm run test:${{ matrix.target }}
        shell: pwsh
        working-directory: ./wasm/packages/okapi
      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          directory: ./wasm/packages/okapi
          token: ${{ secrets.CODECOV_TOKEN }}
        if: ${{ matrix.target == 'node' }}