name: Build Ruby bindings

on:
  pull_request:
    paths:
      - "ruby/**"
      - "proto/**"
      - ".github/workflows/*ruby*"
  push:
    branches:
      - main

jobs:
  build-and-test-ruby:
    runs-on: ${{ matrix.os-artifact[0] }}
    strategy:
      fail-fast: false
      matrix:
        os-artifact: [ [ubuntu-latest, linux], [windows-latest, windows], [macos-latest, macos] ]
        # Due to https://github.com/actions/runner/issues/849, we have to use quotes for '3.0'
        ruby-version: [ 2.7, '3.0' ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1.76.0
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Download workflow artifact
        uses: dawidd6/action-download-artifact@v2.14.0
        with:
          workflow: "build-libs.yml"
          path: ./libs
      - name: Build and run tests
        run: |
          gem install bundler
          gem install rspec
          bundle install
          python ../devops/build_sdks.py --github-token=${{ secrets.API_GITHUB_TOKEN }}
          bundle exec rake
          rake test
          exit 0
        shell: pwsh
        working-directory: ruby
      - name: Upload Unit Test Results - Ruby
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name:  Ruby ${{ matrix.ruby-version }} Unit Test Results (${{ matrix.os-artifact[0] }})
          path: 'ruby/test/reports/TEST-*.xml'

  publish-test-results-ruby:
    name: Publish Ruby Test Results
    needs: build-and-test-ruby
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts
      - name: Publish Test Report - Ruby
        uses: EnricoMi/publish-unit-test-result-action@v1.23
        with:
          files: 'artifacts/**/*.xml'
          check_name: Ruby Test Report