name: Wasm

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    paths:
      - "wasm/**"
      - "proto/**"
      - ".github/workflows/*wasm*"
      - "devops/**"
  push:
    branches:
      - main
    paths:
      - "wasm/**"
      - "proto/**"
      - ".github/workflows/*wasm*"
      - "devops/**"

jobs:
  build_test:
    name: Build, Test
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./wasm
    steps:
      - uses: actions/checkout@v2.4.0
        # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run: npm ci
      - name: Run linters
        uses: wearerequired/lint-action@v1.11.1
        with:
          eslint: true
          eslint_dir: wasm/
          eslint_args: "--ext .ts,.tsx"
      - uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: 'latest'
      - run: |
          rustup toolchain uninstall stable
          rustup toolchain install stable
          rustup toolchain install stable --target wasm32-unknown-unknown
      - run: npm run start
      - run: npm run build
      - run: npm run test
