name: "Swift (release)"

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      packageVersion:
        description: 'Version to build'
        required: true
        default: ''

jobs:
  xcframework:
    name: XCFramework
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: release-downloader
        uses: robinraju/release-downloader@v1.3
        with:
          repository: trinsic-id/okapi
          latest: true
          token: ${{ secrets.API_GITHUB_TOKEN }}
          fileName: "libs.zip"

      - uses: trinsic-id/set-version@v0.1
        id: setversion
        with:
          githubToken: ${{ secrets.API_GITHUB_TOKEN }}
          overrideVersion: ${{ github.event.inputs.packageVersion }}
      - run: |
          python ./devops/build_sdks.py --package-version=${{ steps.setversion.outputs.packageVersion }} --language=none
        working-directory: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Framework
        run: |
          xcodebuild -create-xcframework \
            -library ./libs/macos/libokapi.a -headers ./include/ \
            -library ./libs/ios/libokapi.a -headers ./include/ \
            -library ./libs/ios/libokapi_simulator.a -headers ./include/ \
            -library ./libs/ios/libokapi_maccatalyst.a -headers ./include/ \
            -output OkapiNative.xcframework

          zip -r okapi.xcframework-${{ steps.setversion.outputs.packageVersion }}.zip OkapiNative.xcframework

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: archive
          path: |
            ./*.zip

      - name: Upload to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./okapi.xcframework-${{ steps.setversion.outputs.packageVersion }}.zip
          asset_name: okapi.xcframework-${{ steps.setversion.outputs.packageVersion }}.zip
          tag: ${{ steps.setversion.outputs.releaseVersion }}
          overwrite: false
          body: "Okapi XCFramework"
