name: "Wasm (release)"

on:
  workflow_dispatch:
    inputs:
      packageVersion:
        description: 'Version to build'
        required: true
        default: ''
  workflow_run:
    workflows: ["Release Platform Libraries"]
    branches: ["main", "v?.*"]
    types:
      - completed

jobs:
  publish_npm:
    name: Publish Npm
    environment:
      name: npmjs.com
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./wasm
        shell: pwsh
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: 'latest'
      - run: |
          rustup toolchain uninstall stable
          rustup toolchain install stable
          rustup toolchain install stable --target wasm32-unknown-unknown
      - uses: trinsic-id/set-version@v0.1
        id: setversion
        with:
          githubToken: ${{ secrets.API_GITHUB_TOKEN }}
          overrideVersion: ${{ github.event.inputs.packageVersion }}
      - run: npm set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
      - run: |
          npm install
          npm version ${{ steps.setversion.outputs.packageVersion }} --no-git-tag-version --yes
          npm run build
          npm publish ${{ steps.setversion.outputs.packageVersion }} --no-git-tag-version --yes --no-verify-access
        shell: pwsh
        working-directory: ./wasm/packages/okapi
