name: Java (release)

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      packageVersion:
        description: 'Version to build'
        required: true
        default: ''

jobs:
  build:
    name: Build + Publish Java
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - uses: trinsic-id/set-version@v0.1
        id: setversion
        with:
          githubToken: ${{ secrets.API_GITHUB_TOKEN }}
          overrideVersion: ${{ github.event.inputs.packageVersion }}
      - name: release-downloader
        uses: robinraju/release-downloader@v1.3
        with:
          repository: trinsic-id/okapi
          latest: true
          token: ${{ secrets.API_GITHUB_TOKEN }}
          fileName: "libs.zip"
      - name: Publish package
        run: |
          python ../devops/build_sdks.py --package-version=${{ steps.setversion.outputs.packageVersion }} --language=java
          gradle jar
        working-directory: java
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LD_LIBRARY_PATH: "${{ github.workspace }}/libs"
          DYLD_FALLBACK_LIBRARY_PATH: "${{ github.workspace }}/libs"
          DYLD_LIBRARY_PATH: "${{ github.workspace }}/libs"

      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.API_GITHUB_TOKEN }}
          file: java/build/libs/trinsic-okapi-${{ steps.setversion.outputs.packageVersion }}.jar
          asset_name: trinsic-okapi-${{ steps.setversion.outputs.packageVersion }}.jar
          tag: ${{ steps.setversion.outputs.releaseVersion }}
          overwrite: true
