name: Release Ruby Gem

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Package version - SemVer compliant [N!]N(.N)*[{a|b|rc}N]'
        required: true
        default: ' '
  push:
    branches: [ main ]

jobs:
  build:
    name: Build + Publish Ruby
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.6
        uses: ruby/setup-ruby@v1.76.0
        with:
          ruby-version: 2.7
      - name: Download workflow artifact
        uses: dawidd6/action-download-artifact@v2.14.0
        with:
          workflow: "build-libs.yml"
          path: ./libs
          branch: main
      - name: Install dependencies
        run: ./devops/BuildRuby.ps1 -GitTag "${{ github.ref }}" -PackageVersion "${{ github.event.inputs.version }}"
        shell: pwsh
      - name: Publish gem
        uses: dawidd6/action-publish-gem@v1.2.0
        with:
          api_key: ${{secrets.RUBYGEMS_AUTH_TOKEN}}
          github_token: ${{secrets.GITHUB_TOKEN}}