name: "Wasm (Release)"

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Release Platform Libraries"]
    branches: [main]
    types:
      - completed

jobs:
  publish_npm:
    name: Publish Npm
    environment:
      name: npmjs.com
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./wasm
        shell: pwsh
    steps:
      - uses: actions/checkout@v1
      - uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: 'latest'
      - name: Generate Package Version
        run: |
          $json = Invoke-WebRequest 'https://api.github.com/repos/trinsic-id/okapi/releases/latest' | ConvertFrom-Json
          $version = $json.tag_name.Trim("v")
          echo "PACKAGE_VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf-8 -Append
        shell: pwsh
      - run: npm set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
      - run: |
          npm run start
          npx lerna version $env:PACKAGE_VERSION --no-git-tag-version --yes
          npm run build
          npx lerna publish $env:PACKAGE_VERSION --no-git-tag-version --yes --no-verify-access
