name: Java (release)

on:
  workflow_dispatch:
    inputs:
      packageVersion:
        description: 'Version to build'
        required: true
        default: ''
  # release:
  #   types: [published]
  workflow_run:
    workflows: ["Release Platform Libraries"]
    branches: [main, "v?.*"]
    types:
      - completed

jobs:
  build:
    name: Build + Publish Java
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
      - name: Download workflow artifact
        uses: dawidd6/action-download-artifact@v2.14.0
        with:
          workflow: "build-libs.yml"
          path: ./libs
          branch: main
      - uses: trinsic-id/set-version@v0.1
        id: setversion
        with:
          githubToken: ${{ secrets.API_GITHUB_TOKEN }}
          overrideVersion: ${{ github.event.inputs.packageVersion }}
      - name: Publish package
        run: |
          python ../devops/build_sdks.py --package-version=${{ steps.setversion.outputs.packageVersion }}
          gradle jar
        working-directory: java
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LD_LIBRARY_PATH: "${{ github.workspace }}/libs"
          DYLD_FALLBACK_LIBRARY_PATH: "${{ github.workspace }}/libs"
          DYLD_LIBRARY_PATH: "${{ github.workspace }}/libs"

      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: java/build/libs/trinsic-okapi-${{ steps.setversion.outputs.packageVersion }}.jar
          asset_name: trinsic-okapi-${{ steps.setversion.outputs.packageVersion }}.jar
          tag: ${{ steps.setversion.outputs.releaseVersion }}
          overwrite: true
