name: "Wasm (release)"

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      packageVersion:
        description: 'Version to build'
        required: true
        default: ''  # For beta release: v1.0.0-rc[N]  N=release candidate number https://kevinkreuzer.medium.com/publishing-a-beta-or-alpha-version-to-npm-46035b630dd7

jobs:
  publish_npm:
    name: Publish Npm
    environment:
      name: npmjs.com
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: ['node', 'browser' ]
    defaults:
      run:
        working-directory: ./wasm
        shell: pwsh
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Setup protoc
        uses: arduino/setup-protoc@v1.1.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: 'latest'
      - run: |
          rustup toolchain uninstall stable
          rustup toolchain install stable
          rustup toolchain install stable --target wasm32-unknown-unknown
          npm install -g change-package-name
      - uses: trinsic-id/set-version@v0.1
        id: setversion
        with:
          githubToken: ${{ secrets.API_GITHUB_TOKEN }}
          overrideVersion: ${{ github.event.inputs.packageVersion }}
      - run: npm set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
      - run: |
          npm install
          npx change-package-name "@trinsic/okapi-${{ matrix.target }}"
          npm version ${{ steps.setversion.outputs.packageVersion }} --no-git-tag-version --yes
          npm run build
          npm run build:${{ matrix.target }}
          npm publish --no-git-tag-version --yes --no-verify-access
        shell: pwsh
        working-directory: ./wasm/packages/okapi
