name: Ruby (release)

on:
  workflow_dispatch:
    inputs:
      packageVersion:
        description: 'Version to build'
        required: true
        default: ''
  # release:
  #   types: [published]
  workflow_run:
    workflows: ["Release Platform Libraries"]
    branches: [main, "v?.*"]
    types:
      - completed

jobs:
  build:
    name: Build + Publish Ruby
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.7
        uses: ruby/setup-ruby@v1.76.0
        with:
          ruby-version: 2.7
      - name: Download workflow artifact
        uses: dawidd6/action-download-artifact@v2.17.0
        with:
          workflow: "build-libs.yml"
          path: ./libs
          branch: main
      - name: Build and run tests
        run: |
          gem install bundler
          bundle install
          python ../devops/build_sdks.py --package-version=${{ github.event.inputs.packageVersion }} --language=ruby

          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${{secrets.RUBYGEMS_API_TOKEN}}\n" > $HOME/.gem/credentials
          gem build *.gemspec
          gem push *.gem
        shell: pwsh
        working-directory: ruby
        env:
          API_GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}
          GEM_HOST_API_KEY: ${{secrets.RUBYGEMS_API_TOKEN}}
          RUBY_DLL_PATH: "${{ github.workspace }}/libs"  # Required for Ruby on Windows
          LD_LIBRARY_PATH: "${{ github.workspace }}/libs"
          DYLD_FALLBACK_LIBRARY_PATH: "${{ github.workspace }}/libs"
          DYLD_LIBRARY_PATH: "${{ github.workspace }}/libs"
          