name: "Wasm (release)"

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Release Platform Libraries"]
    branches: ["main", "v?.*"]
    types:
      - completed

jobs:
  publish_npm:
    name: Publish Npm
    environment:
      name: npmjs.com
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./wasm
        shell: pwsh
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: 'latest'
      - run: |
          rustup toolchain uninstall stable
          rustup toolchain install stable
          rustup toolchain install stable --target wasm32-unknown-unknown
      - name: Generate Package Version
        run: |
          $json = Invoke-WebRequest 'https://api.github.com/repos/trinsic-id/okapi/releases/latest' `
            -Headers @{ "Authorization" = "Token $env:API_GITHUB_TOKEN"} | ConvertFrom-Json
          $version = $json.tag_name.Trim("v")
          echo "PACKAGE_VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf-8 -Append
        shell: pwsh
        env:
          API_GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}
      - run: npm set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
      - run: |
          npm run start
          npx lerna version $env:PACKAGE_VERSION --no-git-tag-version --yes
          npm run build
          npx lerna publish $env:PACKAGE_VERSION --no-git-tag-version --yes --no-verify-access
