name: "Python (release)"

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      packageVersion:
        description: 'Version to build'
        required: true
        default: ''

jobs:
  release_pypi:
    name: Python Package deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - uses: trinsic-id/set-version@v0.1
        id: setversion
        with:
          githubToken: ${{ secrets.API_GITHUB_TOKEN }}
          overrideVersion: ${{ github.event.inputs.packageVersion }}
      - name: release-downloader
        uses: robinraju/release-downloader@v1.3
        with:
          repository: trinsic-id/okapi
          latest: true
          token: ${{ secrets.API_GITHUB_TOKEN }}
          fileName: "libs.zip"
      - name: Build, Test, Pack
        run: |
          python -m pip install -r requirements.txt
          python ../devops/build_sdks.py --package-version=${{ steps.setversion.outputs.packageVersion }} --language=python
          python -m build --sdist --wheel --outdir dist/ .
        shell: pwsh
        working-directory: python
        env:
          LD_LIBRARY_PATH: "${{ github.workspace }}/libs"
          API_GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: ./python/dist
