name: "Rust (release)"

on:
  workflow_dispatch:
    inputs:
      packageVersion:
        description: 'Version to build'
        required: true
        default: 'v1.0.0'
  workflow_run:
    workflows: ["Release Platform Libraries"]
    branches: ["main", "v?.*"]
    types:
      - completed
  pull_request:

jobs:
  package_source:
    name: Package Source
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Generate Package Version
        run: |
          $json = Invoke-WebRequest 'https://api.github.com/repos/trinsic-id/okapi/releases/latest' `
            -Headers @{ "Authorization" = "Token $env:API_GITHUB_TOKEN"} | ConvertFrom-Json
          $version = $json.tag_name.Trim("v")
          echo "RELEASE_VERSION=$($json.tag_name)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf-8 -Append
          echo "PACKAGE_VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf-8 -Append
        shell: pwsh
        env:
          API_GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}

      - name: Create Archive
        run: |
          cp -r include native
          rm native/build.rs
          mv native okapi
          tar -czvf okapi-${{ env.PACKAGE_VERSION }}.tar.gz okapi

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: archive
          path: |
            ./*.tar.gz

      - name: Upload to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./okapi-${{ env.PACKAGE_VERSION }}.tar.gz
          asset_name: okapi-${{ env.PACKAGE_VERSION }}.tar.gz
          tag: ${{ env.RELEASE_VERSION }}
          overwrite: false
          body: "Okapi Library Source"

  make_deb:
    name: Package Source
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Generate Package Version
        run: |
          $json = Invoke-WebRequest 'https://api.github.com/repos/trinsic-id/okapi/releases/latest' `
            -Headers @{ "Authorization" = "Token $env:API_GITHUB_TOKEN"} | ConvertFrom-Json
          $version = $json.tag_name.Trim("v")
          echo "RELEASE_VERSION=$($json.tag_name)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf-8 -Append
          echo "PACKAGE_VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf-8 -Append
        shell: pwsh
        env:
          API_GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}

      - name: Build Library
        run: cargo build --release
        working-directory: native

      - name: Create Package (.deb)
        run: |
          cargo install cargo-deb
          cargo deb
        working-directory: native

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: deb
          path: |
            ./native/target/debain/okapi/*.deb

      - name: Upload to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./okapi-${{ env.PACKAGE_VERSION }}.deb
          asset_name: okapi-${{ env.PACKAGE_VERSION }}.deb
          tag: ${{ env.RELEASE_VERSION }}
          overwrite: false
          body: "Okapi Debian Package"