name: Release Ruby Gem

on:
  workflow_dispatch:
    inputs:
      packageVersion:
        description: 'Version to build'
        required: true
        default: ''
  # release:
  #   types: [published]
  workflow_run:
    workflows: ["Release Platform Libraries"]
    branches: [main, "v?.*"]
    types:
      - completed

jobs:
  build:
    name: Build + Publish Ruby
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.6
        uses: ruby/setup-ruby@v1.76.0
        with:
          ruby-version: 2.7
      - name: Download workflow artifact
        uses: dawidd6/action-download-artifact@v2.14.0
        with:
          workflow: "build-libs.yml"
          path: ./libs
          branch: main
      - name: Build and run tests
        run: |
          gem install bundler
          bundle install
          python ../devops/build_sdks.py --package-version=${{ github.event.inputs.packageVersion }}
        shell: pwsh
        working-directory: ruby
        env:
          API_GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}
      - name: Publish gem
        uses: dawidd6/action-publish-gem@v1.2.0
        with:
          path: ruby
          api_key: ${{secrets.RUBYGEMS_API_TOKEN}}
          # Optional, will publish to GitHub Packages if specified
          github_token: ${{secrets.API_GITHUB_TOKEN}}