name: "Golang (release)"

on:
  workflow_dispatch:
    inputs:
      packageVersion:
        description: 'Version to build'
        required: true
        default: ''
  workflow_run:
    workflows: ["Release Platform Libraries"]
    branches: ["main", "v?.*"]
    types:
      - completed

jobs:
  publish_go_tag:
    name: Tag golang
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create tag
        run: |
          git tag "go/${{ github.event.inputs.packageVersion }}" main
          git push "go/${{ github.event.inputs.packageVersion }}" origin