name: Ruby Gem

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build + Publish Ruby
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.6
        uses: ruby/setup-ruby@v1.76.0
        with:
          ruby-version: 2.7
      - name: Download workflow artifact
        uses: dawidd6/action-download-artifact@v2.14.0
        with:
          workflow: "build-libs.yml"
          path: ./libs
          branch: main
      - name: Move libs
        run: |
          New-Item -ItemType Directory -Path "./ruby/libs" -Force
          Copy-Item "./libs/*" -Destination "./ruby/libs" -Recurse -Force -Container:$false
        shell: pwsh
      - name: Install dependencies
        run: |
          gem install bundler
          gem install rspec
          bundle install
        working-directory: ruby
      - name: Publish to GPR
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:github: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem build *.gemspec
          gem push --KEY github --host https://rubygems.pkg.github.com/trinsic-id *.gem
        working-directory: ruby
        env:
          GEM_HOST_API_KEY: "Bearer ${{secrets.GITHUB_TOKEN}}"

      # - name: Publish to RubyGems
        # run: |
          # mkdir -p $HOME/.gem
          # touch $HOME/.gem/credentials
          # chmod 0600 $HOME/.gem/credentials
          # printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          # gem build *.gemspec
          # gem push *.gem
        # env:
          # GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"