name: Release Python SDK

on:
  workflow_dispatch:
    inputs:
      packageVersion:
        description: 'Version to build'
        required: true
        default: ''
  # release:
  #   types: [published]
  workflow_run:
    workflows: ["Release Platform Libraries"]
    branches: [main, "v?.*"]
    types:
      - completed

jobs:
  release_pypi:
    name: Python Package deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Download workflow artifact
        uses: dawidd6/action-download-artifact@v2.14.0
        with:
          workflow: "build-libs.yml"
          path: ./libs
          branch: main
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Build, Test, Pack
        run: |
          python -m pip install -r requirements.txt
          python -m pip install build
          python ../devops/build_sdks.py --github-token=${{ secrets.API_GITHUB_TOKEN }} --package-version=${{ github.event.inputs.packageVersion }}
          python -m build --sdist --wheel --outdir dist/ .
        shell: pwsh
        working-directory: python
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: ./python/dist
