name: Ruby (release)

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      packageVersion:
        description: 'Version to build'
        required: true
        default: ''

jobs:
  build:
    name: Build + Publish Ruby
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.7
        uses: ruby/setup-ruby@v1.76.0
        with:
          ruby-version: 2.7
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - uses: trinsic-id/set-version@v0.1
        id: setversion
        with:
          githubToken: ${{ secrets.API_GITHUB_TOKEN }}
          overrideVersion: ${{ github.event.inputs.packageVersion }}
      - name: release-downloader
        uses: robinraju/release-downloader@v1.3
        with:
          repository: trinsic-id/okapi
          latest: true
          token: ${{ secrets.API_GITHUB_TOKEN }}
          fileName: "libs.zip"
      - name: Build and run tests
        run: |
          gem install bundler
          bundle install
          python ../devops/build_sdks.py --package-version=${{ steps.setversion.outputs.packageVersion }} --language=ruby

          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${{secrets.RUBYGEMS_API_TOKEN}}\n" > $HOME/.gem/credentials
          gem build *.gemspec
          gem push *.gem
        shell: pwsh
        working-directory: ruby
        env:
          API_GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}
          GEM_HOST_API_KEY: ${{secrets.RUBYGEMS_API_TOKEN}}
          RUBY_DLL_PATH: "${{ github.workspace }}/libs"  # Required for Ruby on Windows
          LD_LIBRARY_PATH: "${{ github.workspace }}/libs"
          DYLD_FALLBACK_LIBRARY_PATH: "${{ github.workspace }}/libs"
          DYLD_LIBRARY_PATH: "${{ github.workspace }}/libs"
          